### PR TITLE
Forging Chance Corrections and Baby Penalty

### LINKED ISSUE #9921: Forging Chances
### rAthena Hash

9215090

### Client Date

2021-11-03

### Server Mode

Pre-Renewal, Renewal

### Result

Base bonus: 0%
Bonus per weapon level: 50%/30%/20%/10% 
Bonus per anvil level: 10%/5%/**3%**/0%
Elemental Stone penalty: 20%
3rd Job Bonus: 14%

Baby penalty of 50% on ALL crafting.

Note: We actually put 50% base and then substract weapon level instead of having it as a bonus, but I calculated it out here for easier comparison.

### Expected Result

Base bonus: 0.1%~10% (random)
Bonus per weapon level: 40%/20%/13.3%/0%
Bonus per anvil level: 10%/5%/**2.5%**/0%
Elemental Stone penalty: 25%
3rd Job Bonus: 0.2% per job level

Baby penalty of 30% on only Weapon crafting and Brewing.

### How to Reproduce

Use forging and verify rates.

### Official Information

Verified.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9921

* **Server Mode**: Both

**Description of Pull Request**: 

- Added a random 0.1%~10% base chance bonus to all blacksmith forging (including ores)
- Reduced base success chance of weapon crafting by 10%
- Increased element stone penalty from 20% to 25%
- Decreased Oridecon Anvil bonus from 3% to 2.5%
- Third jobs no longer get a 14% chance bonus; instead it's just the regular 0.2% per job level bonus
- The baby chance penalty now only applies to weapon forging and brewing
- Reduced baby chance penalty from 50% to 30%
- Oridecon Research will no longer increase success chance by default
  * Added a config to make it optionally work as before
- Fixes #9921

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -12917,10 +12917,12 @@ bool skill_produce_mix(map_session_data *sd, uint16 skill_id, t_itemid nameid, i
 			case BS_ENCHANTEDSTONE:
 				// Ores & Metals Refining - skill bonuses are straight from kRO website [DracoRPG]
 				i = pc_checkskill(sd,skill_id);
-				make_per = sd->status.job_level*20 + status->dex*10 + status->luk*10; //Base chance
+				//Base chance
+				make_per = sd->status.job_level * 20 + status->dex * 10 + status->luk * 10;
```
Comment (Lemongrass3110) [inline src/map/skill.cpp]:
```suggestion
				make_per = sd->status.job_level * 20;
				make_per += status->dex * 10;
				make_per += status->luk * 10;
```

File: src/map/skill.cpp [hunk 2]
```diff
@@ -13174,36 +13179,39 @@ bool skill_produce_mix(map_session_data *sd, uint16 skill_id, t_itemid nameid, i
 				make_per = 5000;
 				break;
 		}
-	} else { // Weapon Forging - skill bonuses are straight from kRO website, other things from a jRO calculator [DracoRPG]
-		make_per = 5000 + ((sd->class_&JOBL_THIRD)?1400:sd->status.job_level*20) + status->dex*10 + status->luk*10; // Base
+	} else { // Weapon Forging
+		//Base chance
+		make_per = sd->status.job_level * 20 + status->dex * 10 + status->luk * 10;
```
Comment (Lemongrass3110) [inline src/map/skill.cpp]:
```suggestion
		make_per = sd->status.job_level * 20;
		make_per += status->dex * 10;
		make_per += status->luk * 10;
```

File: src/map/skill.cpp [hunk 3]
```diff
@@ -13174,36 +13179,39 @@ bool skill_produce_mix(map_session_data *sd, uint16 skill_id, t_itemid nameid, i
...
+		make_per += rnd_value(1, 100) * 10;
+		// Weapon level base chance
+		if (wlv > 0 && wlv < 4) {
+			make_per += (4 / wlv) * 1000; //+40/+20/+10/+0
```
Comment (Lemongrass3110) [inline src/map/skill.cpp]:
```suggestion
			make_per += (4 / wlv) * 1000; //+40/+20/+10
```
Level 4 is excluded by the if above, so it looks strange to see 4 values here.

Why did you not like the old inverse method (malus)?

**Review by Lemongrass3110 — APPROVED** [review]

File: src/map/skill.cpp (hunk 3 above)
Comment (Playtester) [reply src/map/skill.cpp]: I wanted to structure it more like official, so it's easier to compare.
