### PR TITLE
Loot Protection Time Fixes

### LINKED ISSUE #9240: Loot Protection Times too short
### rAthena Hash

aa676e6

### Client Date

2021-11-03

### Server Mode

Pre-Renewal, Renewal

### Result

When player A kills a monster, any other player can pick up the item after 3000ms (10000ms for MVPs)

When player A+B kill a monster, any other player can pick up the item after 4000ms. (20000ms for MVPs)

When player A+B+C kill a monster, any other player can pick up the item after 5000ms. (22000ms for MVPs)

### Expected Result

Regardless of how many players killed a monster, players that weren't in the damage log need to wait 7000ms to pick up the item. (22000ms for bosses)

When killing a normal monster, the second player can loot items after 3000ms and the third player can loot items after 5000ms.

### How to Reproduce

Kill a monster, then try to loot the item with another player.

### Official Information

Verified by tests.

Player A kills monster -> Player B needs to wait 7000ms to pick up the item
Player A+B kill a monster (A gets loot priority) -> Player B needs to wait 3000ms to pick up the item

Player A kills boss monster -> Player B needs to wait 22000ms to pick up the item

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9240 

* **Server Mode**: Both

**Description of Pull Request**: 

- Fixed Loot Protection time being calculated incorrectly when there was no second or third attacker
  * Bystanders can now always only loot after 7000ms on normal monsters and 22000ms on boss monsters
  * Values are of course still configurable in drops.conf
- Any loot from bosses and MVPs now uses the extended protection time
  * This was previously only applied to MVP reward items that drop to the ground when inventory was full
- Corrected the default protection times
  * Normal Monster -> second after 3000ms, third after 5000ms, anyone else after 7000ms
  * Boss Monster -> second after 10000ms, third after 20000ms, anyone else after 22000ms
- Fixes #9240

### CODE REVIEW

File: src/map/map.cpp [hunk 1]
```diff
@@ -2028,12 +2028,21 @@ int32 map_addflooritem(struct item *item, int32 amount, int16 m, int16 x, int16
...
+	if (mob_id > 0) {
+		std::shared_ptr<s_mob_db> mob = mob_db.find(mob_id);
+		// Boss and MVP drops both have prelonged loot protection
+		if (mob != nullptr && mob->get_bosstype() != BOSSTYPE_NONE)
+			extend_protection = true;
+	}
+
 	fitem->first_get_charid = first_charid;
-	fitem->first_get_tick = gettick() + (flags&1 ? battle_config.mvp_item_first_get_time : battle_config.item_first_get_time);
+	fitem->first_get_tick = gettick() + (extend_protection ? battle_config.mvp_item_first_get_time : battle_config.item_first_get_time);
```
Comment (Lemongrass3110) [inline src/map/map.cpp:2041]: Cant we assign all char ids first and then only have one if?

File: conf/battle/drops.conf [hunk 2]
```diff
@@ -18,20 +18,23 @@ item_first_get_time: 3000
...
-item_second_get_time: 1000
+item_second_get_time: 2000
 
 // Grace time during which only the first, second and third person who did the most damage to a monster can get the item? (in milliseconds)
 // (Takes effect after the item_second_get_time elapses)
-item_third_get_time: 1000
+item_third_get_time: 2000
 
-// Grace time to apply to MvP reward items when the Most Valuable Player can't get the prize item and it drops on the ground? (in milliseconds)
+// Grace time during which only the person who did the most damage to a boss can get the item? (in milliseconds)
```
Comment (Lemongrass3110) [inline conf/battle/drops.conf:27]:
```suggestion
// How long is the grace time, during which only the player, who did the most damage to a boss, can get the item? (in milliseconds)
```

File: conf/battle/drops.conf [hunk 3]
```diff
@@ -18,20 +18,23 @@ item_first_get_time: 3000
...
+// Also applies to MvP reward items when the Most Valuable Player can't get the prize item and it drops on the ground
```
Comment (Lemongrass3110) [inline conf/battle/drops.conf:28]:
```suggestion
// Also applies to MvP reward items, when the Most valuable Player can't get the prize item and it drops on the ground
```

File: conf/battle/drops.conf [hunk 4]
```diff
@@ -18,20 +18,23 @@ item_first_get_time: 3000
...
 mvp_item_first_get_time: 10000
 
-// Grace time for the first and second MvP so they can get the item? (in milliseconds)
+// Grace time during which only the first and second person who did the most damage to a boss can get the item? (in milliseconds)
```
Comment (Lemongrass3110) [inline conf/battle/drops.conf:31]:
```suggestion
// How long is the grace time, during which only the first and second player, who did the most damage to a boss, can get the item? (in milliseconds)
```

File: conf/battle/drops.conf [hunk 5]
```diff
@@ -18,20 +18,23 @@ item_first_get_time: 3000
...
+// Also applies to MvP reward items when first and second MVP can't get the prize item and it drops on the ground
```
Comment (Lemongrass3110) [inline conf/battle/drops.conf:32]:
```suggestion
// Also applies to MvP reward items, when first and second MvP can't get the prize item and it drops on the ground
```

File: conf/battle/drops.conf [hunk 6]
```diff
@@ -18,20 +18,23 @@ item_first_get_time: 3000
...
 // (Takes effect after mvp_item_first_get_time elapses)
 mvp_item_second_get_time: 10000
 
-// Grace time for the first, second and third MvP so they can get the item? (in milliseconds)
+// Grace time during which only the first, second and third person who did the most damage to a boss can get the item? (in milliseconds)
```
Comment (Lemongrass3110) [inline conf/battle/drops.conf:36]:
```suggestion
// How long is the grace time, during which only the first, second and third player, who did the most damage to a boss, can get the item? (in milliseconds)
```

File: conf/battle/drops.conf [hunk 7]
```diff
@@ -18,20 +18,23 @@ item_first_get_time: 3000
...
+// Also applies to MvP reward items when first, second and third MvP can't get the prize item and it drops on the ground
```
Comment (Lemongrass3110) [inline conf/battle/drops.conf:37]:
```suggestion
// Also applies to MvP reward items, when first, second and third MvP can't get the prize item and it drops on the ground
```

File: src/map/pc.cpp [hunk 8]
```diff
@@ -6103,25 +6103,31 @@ bool pc_takeitem(map_session_data *sd,struct flooritem_data *fitem)
 	if (sd->status.party_id)
 		p = party_search(sd->status.party_id);
 
-	if (fitem->first_get_charid > 0 && fitem->first_get_charid != sd->status.char_id) {
-		map_session_data *first_sd = map_charid2sd(fitem->first_get_charid);
+	if (fitem->first_get_charid == 0 || fitem->first_get_charid != sd->status.char_id) {
```
[the remark this answers is not in the document]
Comment (Playtester) [reply src/map/pc.cpp:6106]: I don't understand this. It's currently bugged that the delay doesn't apply correctly and this code line (and the ones below) fixes it to work correctly.

It's also mentioned in the PR description:
> Fixed Loot Protection time being calculated incorrectly when there was no second or third attacker
> Bystanders can now always only loot after 7000ms on normal monsters and 22000ms on boss monsters

File: src/map/map.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/map.cpp:2041]: Do you mean:
```
if (extend_protection) {
  fitem->first_get_tick = battle_config.mvp_item_first_get_time;
  fitem->second_get_tick = battle_config.mvp_item_second_get_time;
  fitem->third_get_tick = battle_config.mvp_item_third_get_time;
} else {
  fitem->first_get_tick = battle_config.item_first_get_time;
  fitem->second_get_tick = battle_config.item_second_get_time;
  fitem->third_get_tick = battle_config.item_third_get_time;
}
```
Like this?

File: conf/battle/drops.conf (hunk 7 above)
Comment (Playtester) [reply conf/battle/drops.conf:37]: This would be incorrect grammar, in English you don't put commas in front of "when" and "if".
https://www.pristineword.com/comma-when/

File: conf/battle/drops.conf (hunk 3 above)
Comment (Playtester) [reply conf/battle/drops.conf:28]: Writing the v lower case seems strange to me. Do you really prefer that?

File: src/map/map.cpp (hunk 1 above)
Comment (Lemongrass3110) [reply src/map/map.cpp:2041]: Yeah like this, but not removing adding the first tick to the second and the second to the third

File: conf/battle/drops.conf (hunk 3 above)
Comment (Lemongrass3110) [reply conf/battle/drops.conf:28]: I dont care. But keep it consistent. It is different everywhere in this PR

File: conf/battle/drops.conf (hunk 7 above)
Comment (Lemongrass3110) [reply conf/battle/drops.conf:37]: I think you misunderstand your own link.
In your link it is 3. It is a parenthetic expression, that further describes the situation, in which this config applies.
It may be unnecssary, but not incorrect.

Comment (Playtester) [reply conf/battle/drops.conf:37]: This is not a parenthetic expression, it's clearly an independent clause.

Comment (Lemongrass3110) [reply conf/battle/drops.conf:37]: "it can be easily omitted without changing the meaning of the sentence"

=> It applies to MVP reward items.
The rest is just additional - too much info. Of course it can only happen if they drop to the ground, thus this can be left out and is parenthetic.

File: conf/battle/drops.conf (hunk 3 above)
Comment (Daegaladh) [reply conf/battle/drops.conf:28]: It's mixed all along the code, so we better start changing them to uppercase

File: src/map/map.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/map.cpp]: Done.

File: src/map/pc.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (Playtester) [reply src/map/pc.cpp]: Reworked the code completely now. Please check.

**Review by Daegaladh — APPROVED** [review]

File: src/map/map.cpp [hunk 9]
```diff
@@ -2028,12 +2028,26 @@ int32 map_addflooritem(struct item *item, int32 amount, int16 m, int16 x, int16
 		return 0;
 	}
 
+	// If item is flagged as MVP item or dropped by bosses, it is protected for longer
+	bool extend_protection = (flags&1);
+	if (!extend_protection && mob_id > 0) {
+		// Boss and MVP drops both have prelonged loot protection
+		if (auto mob_db.find(mob_id); mob != nullptr && mob->get_bosstype() != BOSSTYPE_NONE)
```
Comment (Daegaladh) [inline src/map/map.cpp:2035]:
```suggestion
		if (auto mob = mob_db.find(mob_id); mob != nullptr && mob->get_bosstype() != BOSSTYPE_NONE)
```
