### PR TITLE
Coma Rework, Exp Calc Type, Fiber Lock Range

### LINKED ISSUE #8279: Coma effect and trigger conditions
### rAthena Hash

2963e52

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

Coma sets SP to 0.
Coma does not trigger on Provoke.
An attack that causes Coma still deals damage.

### Relevant Log Output

_No response_

### Expected Result

Coma sets SP to 1.
Coma can trigger on Provoke. It even triggers on yourself on Self Provoke, so using Aloevera can make you Coma yourself. It does not trigger on any other nodamage skills.
An attack that causes Coma will show normal damage but does not actually deal damage. If you had 100% Coma chance, you can effectively never kill anything.

### How to Reproduce

Set Coma chance on Lord of the Death Card to 100%. Then use Provoke / Aloevera or other nodamage skills.

Use Grand Cross at 100% Coma chance (you will not die from self damage).

### Official Information

Verified by various tests.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #8279 

* **Server Mode**: Both

**Description of Pull Request**: 

- Coma item bonus is no longer an additional effect / status change, but instead replaces the attack damage with setting HP/SP to 1
  * That means Coma attacks will never kill someone, even if the original attack would be lethal
  * When doing a Coma attack, the attack displays the original damage and this is also what counts towards the mob damage log
- Coma is checked for every single event that applies damage, including reflect damage, and for Provoke / Self Provoke
  * Some Renewal-only effects couldn't be tested and were left unchanged (e.g. damage from White Imprison)
- Coma now sets SP to 1 instead of 0
- bComaRace, bWeaponComaRace and bWeaponComaEle won't work on bosses, GVG and battlefield objects
- bComaClass and bWeaponComaClass no longer work on GVG and battlefield objects, but can work on bosses if you specify Class_Boss or Class_All
- Edge is now defined to only work on normal monster
- The default exp_calc_type 0 no longer counts the first attacker twice and instead works like on official servers
- Added a new exp_calc_type 2 that counts the first attacker twice as previously
- The damage logged will now include overkill damage on exp_calc_type 0 and 2, but not count Coma damage (it will count the damage you would have originally dealt instead)
- Fiber Lock now has a range of 9 instead of 7
- Fixes #8279

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -254,33 +256,42 @@ struct block_list* battle_getenemyarea(struct block_list *src, int x, int y, int
...
 * @param isspdamage: If the damage is done to SP
 * @param tick: Current tick
-*------------------------------------------*/
-void battle_damage(struct block_list *src, struct block_list *target, int64 damage, t_tick delay, uint16 skill_lv, uint16 skill_id, enum damage_lv dmg_lv, unsigned short attack_type, bool additional_effects, t_tick tick, bool isspdamage) {
+* @return HP+SP+AP (0 if HP/SP/AP remained unchanged)
+*/
+int battle_damage(struct block_list *src, struct block_list *target, int64 damage, t_tick delay, uint16 skill_lv, uint16 skill_id, enum damage_lv dmg_lv, unsigned short attack_type, bool additional_effects, t_tick tick, bool isspdamage) {
+	int dmg_change;
+	map_session_data* sd = nullptr;
+	if (src)
```
Comment (aleos89) [inline src/map/battle.cpp:280]: Can src be null? If not just move this into the sd define. It's not checked elsewhere so it would crash for any other case.

**Review by aleos89 — APPROVED** [review]

File: src/map/mob.cpp [hunk 2]
```diff
@@ -2675,14 +2674,16 @@ int mob_dead(struct mob_data *md, struct block_list *src, int type)
...
+			if (battle_config.exp_calc_type == 1 && md->tdmg) {
+				// eAthena's exp formula based on max hp
+				per = (double)md->dmglog[i].dmg / (double)status->max_hp;
+			}
 			else {
-				//eAthena's exp formula based on max hp.
-				per = (double)md->dmglog[i].dmg/(double)status->max_hp;
-				if (per > 2) per = 2; // prevents unlimited exp gain
+				// Aegis's exp formula based on total damage
+				per = (double)md->dmglog[i].dmg / (double)md->tdmg;
```
Comment (Atemo) [inline src/map/mob.cpp:2683]: `md->tdmg` is no longer checked against 0 here

File: src/map/battle.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/battle.cpp:280]: src can be NULL if you don't want the attack to log the damage. There were actually a few calls that passed NULL into status_damage before, but I guess I replaced them now.

I think the function should work if src is NULL though, so it shouldn't crash.

File: src/map/mob.cpp (hunk 2 above)
Comment (Playtester) [reply src/map/mob.cpp:2683]: Good spot, will fix that.
