### PR TITLE
Fixes instance map names over 1000

### LINKED ISSUE #4915: instance_count will start to error at 1000
* rAthena Hash: https://github.com/rathena/rathena/commit/d1719f670ffa77b6849bc97817b4d047c6970afd

* Client Date: 20180621

* Server Mode: Renewal

* Description of Issue:

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #4915

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Fixes instance map names when it reaches 1000.
Thanks to @voyfmyuh!

### CODE REVIEW

File: src/map/instance.cpp [hunk 1]
```diff
@@ -730,7 +730,7 @@ int16 instance_mapid(int16 m, int instance_id)
 
 			if (!(strchr(iname, '@')) && strlen(iname) > 8) {
 				memmove((void*)iname, iname + (strlen(iname) - 9), strlen(iname));
-				snprintf(alt_name, sizeof(alt_name), "%d#%s", instance_id, iname);
+				snprintf(alt_name, sizeof(alt_name), "%d#%s", (instance_id % 1000), iname);
 			}
 			else
 				snprintf(alt_name, sizeof(alt_name), "%.3d%s", instance_id, iname);
```
Comment (Atemo) [inline src/map/instance.cpp:736]:
```suggestion
				snprintf(alt_name, sizeof(alt_name), "%.3d%s", (instance_id % 1000), iname);
```
