### PR TITLE
Synchronize Damage Feature

### LINKED ISSUE #259: Movement desync
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce & Description:

The dev guys already corrected a lot of things regarding the movement lag/desync issue, but still there is at least one issue:

When I get hit and in my desire to break free I click somewhere to move, the character displays the flintch movement for it's whole duration, but in the meantime the server receives my movement commands and starts to move my character on the server side. On the client side this results in my character jumping from one location to another.

So, the client we usually use is an official one, with some minor modifications. On the other hand, the server side was written from sketch. So I think it is logical to say, that we should follow the client's "guide" if we want to mimic the official behav. If the client says "you shouldn't move during hitlock", then why do we allow the server side to move the player? Or perhaps we should allow the player to move, because the client still sends the move commands during hitlock, but we miss a packet that tells the client to cancel the flintch movement. Either way, it is pretty annoying that if a single mob hits us during movement, we desync in movement.

Another theory I have is that in case of monsters, the hitlock works better, becuause they simply won't issue a new movetoxy() command during their hitlock/flintch time, but since players can click whenever they wish, they do issue a move command in the urge to break free, and maybe this case is not handled correctly.

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #259 

* **Server Mode**: Both

**Description of Pull Request**: 

- Added a new monster stat "ClientAttackMotion" to mob_db.yml which is the time from when a monster attacks until which the damage shows on the client at 1x speed
- Added a new config synchronize_damage; when set to "yes", the client will display the damage of normal monster attacks at the exact time it is applied on the server, removing position lag (fixes #259)

### CODE REVIEW

**Comment by Playtester** [comment]
Note: The value for Anubis in the mob_db.yml file seems to be incorrect, @aleos89 is currently investigating this.

File: src/map/status.hpp [hunk 1]
```diff
@@ -3172,7 +3172,7 @@ struct status_data {
 #endif
 		matk_min, matk_max,
 		speed,
-		amotion, adelay, dmotion;
+		amotion, clientamotion, adelay, dmotion;
```
Comment (aleos89) [inline src/map/status.hpp:3175]:
```suggestion
		amotion, client_amotion, adelay, dmotion;
```
If `clientamotion` is too hard to read without snake-case then feel free to adjust it!

File: src/map/battle.cpp [hunk 2]
```diff
@@ -411,7 +411,14 @@ int battle_delay_damage(t_tick tick, int amotion, struct block_list *src, struct
 	dat->additional_effects = additional_effects;
 	dat->src_type = src->type;
 	dat->isspdamage = isspdamage;
-	if (src->type != BL_PC && amotion > 1000)
+	if (skill_id == 0 && src->type == BL_MOB && battle_config.synchronize_damage) {
+		mob_data* md = BL_CAST(BL_MOB, src);
+		// The client refuses to display animations slower than 1x speed
+		// So we need to shorten AttackMotion to be in-sync with the client in this case
+		if (amotion > md->status.clientamotion)
```
Comment (Atemo) [inline src/map/battle.cpp:418]:
```suggestion
		if (md != nullptr && amotion > md->status.clientamotion)
```

File: src/map/clif.cpp [hunk 3]
```diff
@@ -5242,6 +5242,13 @@ int clif_damage(struct block_list* src, struct block_list* dst, t_tick tick, int
 		}
 	}
 
+	// Calculate what sdelay to send to the client so it applies damage at the same time as the server
+	if (src->type == BL_MOB && battle_config.synchronize_damage) {
+		mob_data* md = BL_CAST(BL_MOB, src);
+		// The client only accepts values between 0 and 432; 432 stands for 1x animation speed
+		sdelay = sdelay * 432 / md->status.clientamotion;
```
Comment (Atemo) [inline src/map/clif.cpp:5249]:
```suggestion
		if (md != nullptr && md->status.clientamotion != 0)
			sdelay = sdelay * 432 / md->status.clientamotion;
```

File: src/map/mob.cpp [hunk 4]
```diff
@@ -4811,6 +4811,18 @@ uint64 MobDatabase::parseBodyNode(const ryml::NodeRef& node) {
...
+	if (this->nodeExists(node, "ClientAttackMotion")) {
+		uint16 speed;
+
+		if (!this->asUInt16(node, "ClientAttackMotion", speed))
+			return 0;
+
+		mob->status.clientamotion = cap_value(speed, 1, USHRT_MAX);
+	} else {
+		if (!exists)
+			mob->status.clientamotion = cap_value(mob->status.amotion, 1, USHRT_MAX);
```
Comment (Atemo) [inline src/map/mob.cpp:4823]: How about putting a default in s_mob_db constructor for cases like player clone?

**Comment by SapitoSucio** [comment]
This seems nice :O

File: src/map/mob.cpp (hunk 4 above)
Comment (Playtester) [reply src/map/mob.cpp:4823]: @Atemo I assume that would only work for fixed values, but we could put 432 as default there I guess?

File: src/map/battle.cpp (hunk 2 above)
Comment (Playtester) [reply src/map/battle.cpp:419]: I was wondering if md can be nullptr at all because I check for bl->type beforehand.

File: src/map/status.hpp (hunk 1 above)
Comment (Playtester) [reply src/map/status.hpp:3175]: I think it's fine.

File: src/map/clif.cpp (hunk 3 above)
Comment (Lemongrass3110) [reply src/map/clif.cpp]: Here it cannot be null, as "src" was already accessed before and "type" was already verified

File: src/map/battle.cpp [hunk 5]
```diff
@@ -411,7 +416,12 @@ int battle_delay_damage(t_tick tick, int amotion, struct block_list *src, struct
 	dat->additional_effects = additional_effects;
 	dat->src_type = src->type;
 	dat->isspdamage = isspdamage;
-	if (src->type != BL_PC && amotion > 1000)
+	if (skill_id == 0 && src->type == BL_MOB && battle_config.synchronize_damage && amotion > status_get_clientamotion(src)) {
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:419]:
```suggestion
	if (battle_config.synchronize_damage && skill_id == 0 && src->type == BL_MOB && amotion > status_get_clientamotion(src)) {
```
Feature check first, so that it fails as fast as possible.

File: src/map/battle.cpp [hunk 6]
```diff
@@ -393,7 +393,12 @@ int battle_delay_damage(t_tick tick, int amotion, struct block_list *src, struct
 		damage = 0;
 	}
 
-	if ( !battle_config.delay_battle_damage || amotion <= 1 ) {
+	// If the synchronize damage feature is activated then disabling delay battle damage should only affect skills (for monsters)
+	// If clientamotion is 1 or lower for monsters, we can apply damage directly for normal attacks and don't need to create a timer
+	// Same applies for all types, normal attacks and skills if amotion is 1 or lower
+	if ((!battle_config.delay_battle_damage && (src->type != BL_MOB || !battle_config.synchronize_damage || skill_id != 0))
+		|| (skill_id == 0 && src->type == BL_MOB && battle_config.synchronize_damage && status_get_clientamotion(src) <= 1)
+		|| amotion <= 1) {
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:401]: This if is too long again.
It also changes existing behavor.

File: src/map/clif.cpp [hunk 7]
```diff
@@ -5242,6 +5242,12 @@ int clif_damage(struct block_list* src, struct block_list* dst, t_tick tick, int
 		}
 	}
 
+	// Calculate what sdelay to send to the client so it applies damage at the same time as the server
+	if (src->type == BL_MOB && battle_config.synchronize_damage && status_get_clientamotion(src) != 0) {
```
Comment (Lemongrass3110) [inline src/map/clif.cpp:5246]:
```suggestion
	if (battle_config.synchronize_damage && src->type == BL_MOB && status_get_clientamotion(src) != 0) {
```
Feature check first, so that it fails as fast as possible.

File: src/map/clif.cpp [hunk 8]
```diff
@@ -5242,6 +5242,12 @@ int clif_damage(struct block_list* src, struct block_list* dst, t_tick tick, int
...
+		// The client only accepts values between 0 and 432; 432 stands for 1x animation speed
+		sdelay = sdelay * 432 / status_get_clientamotion(src);
```
Comment (Lemongrass3110) [inline src/map/clif.cpp:5248]: Would be nice to define a constant somewhere.

File: src/map/mob.cpp [hunk 9]
```diff
@@ -4811,6 +4812,18 @@ uint64 MobDatabase::parseBodyNode(const ryml::NodeRef& node) {
...
```
Comment (Lemongrass3110) [inline src/map/mob.cpp:4824]:
```suggestion
			mob->status.clientamotion = cap_value(mob->status.amotion, 1, 432);
```
Or a newly introduced constant.

File: src/map/mob.cpp [hunk 10]
```diff
@@ -4811,6 +4812,18 @@ uint64 MobDatabase::parseBodyNode(const ryml::NodeRef& node) {
 		mob->status.amotion = cap_value(speed, battle_config.monster_max_aspd, 2000);
 	}
 
+	if (this->nodeExists(node, "ClientAttackMotion")) {
+		uint16 speed;
+
+		if (!this->asUInt16(node, "ClientAttackMotion", speed))
+			return 0;
+
+		mob->status.clientamotion = cap_value(speed, 1, USHRT_MAX);
```
Comment (Lemongrass3110) [inline src/map/mob.cpp:4821]: We should not use cap value here.
Give a proper warning for 0 or > 432 (or newly defined constant).

**Review by Lemongrass3110 — CHANGES_REQUESTED** [review]

File: src/map/battle.cpp (hunk 6 above)
Comment (Playtester) [reply src/map/battle.cpp:401]: It does not change existing behavior. You'd need to enable the new feature for the behavior to change.

But maybe should just adjust amotion in more simple checks beforehand.

File: src/map/mob.cpp (hunk 9 above)
Comment (Playtester) [reply src/map/mob.cpp:4824]: Needs to stay capped to USHRT_MAX or it won't work. There are plenty of official values higher than 432.

File: src/map/mob.cpp (hunk 10 above)
Comment (Playtester) [reply src/map/mob.cpp:4821]: Those values do exist in the files. The reason I cap 0 to 1 is simply to prevent the risk of division by 0.
Values above 432 are valid.

File: src/map/clif.cpp (hunk 8 above)
Comment (Playtester) [reply src/map/clif.cpp:5248]: Yeah we can do that, but this is the only place where it's used.

File: src/map/battle.cpp (hunk 6 above)
Comment (Playtester) [reply src/map/battle.cpp]: Split into 3 if() checks.

File: src/map/clif.cpp (hunk 8 above)
Comment (Playtester) [reply src/map/clif.cpp]: Added constant.

File: conf/battle/client.conf [hunk 11]
```diff
@@ -169,3 +169,10 @@ macro_detection_punishment: 0
 // Amount of time in minutes that the punishment type is active for. Use 0 for infinite.
 // Official: 0
 macro_detection_punishment_time: 0
+
+// Should the damage timing be synchronized between the client and server?
+// This is not official behavior, but it removes the position lag after being hit.
+// This setting only affects normal monster attacks, unless you set "delay_battle_damage" in battle.conf to "no".
+// If you do, most skills will also be in-sync as skills usually show their damage immediately.
+// Tired of Dark Illusion hitting you 5 seconds too late? Then turn this on. (Note 1)
+synchronize_damage: no
```
Comment (Lemongrass3110) [inline conf/battle/client.conf:178]: Should be moved to conf/battle/battle.conf right after delay_battle_damage

File: src/map/clif.cpp [hunk 12]
```diff
@@ -5242,6 +5244,12 @@ int clif_damage(struct block_list* src, struct block_list* dst, t_tick tick, int
 		}
 	}
 
+	// Calculate what sdelay to send to the client so it applies damage at the same time as the server
+	if (battle_config.synchronize_damage && src->type == BL_MOB && status_get_clientamotion(src) != 0) {
```
Comment (Lemongrass3110) [inline src/map/clif.cpp:5248]: status_get_clientamotion will always return != 0, since you cap it to 1

File: src/map/battle.cpp [hunk 13]
```diff
@@ -393,7 +393,16 @@ int battle_delay_damage(t_tick tick, int amotion, struct block_list *src, struct
...
+	// Check for delay battle damage config
+	// If the synchronize damage feature is activated then disabling the config should only affect skills (for monsters)
+	if (!battle_config.delay_battle_damage && (!battle_config.synchronize_damage || skill_id != 0 || src->type != BL_MOB))
+		amotion = 1;
+	// If clientamotion is 1 or lower for monsters, we can apply damage directly for normal attacks and don't need to create a timer
+	else if (battle_config.synchronize_damage && skill_id == 0 && src->type == BL_MOB && status_get_clientamotion(src) <= 1)
+		amotion = 1;
+
+	// Skip creation of timer
+	if (amotion <= 1) {
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:405]:
```suggestion
	// The client refuses to display animations slower than 1x speed
	// So we need to shorten AttackMotion to be in-sync with the client in this case
	if( battle_config.synchronize_damage && skill_id == 0 && src->type == BL_MOB && amotion > status_get_clientamotion(src) ){
		amotion = status_get_clientamotion(src);
	}

	if ( !battle_config.delay_battle_damage || amotion <= 1 ) {
```

File: src/map/battle.cpp [hunk 14]
```diff
@@ -411,7 +420,12 @@ int battle_delay_damage(t_tick tick, int amotion, struct block_list *src, struct
 	dat->additional_effects = additional_effects;
 	dat->src_type = src->type;
 	dat->isspdamage = isspdamage;
-	if (src->type != BL_PC && amotion > 1000)
+	if (battle_config.synchronize_damage && skill_id == 0 && src->type == BL_MOB && amotion > status_get_clientamotion(src)) {
+		// The client refuses to display animations slower than 1x speed
+		// So we need to shorten AttackMotion to be in-sync with the client in this case
+		amotion = status_get_clientamotion(src);
+	}
+	else if (src->type != BL_PC && amotion > 1000)
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:428]:
```suggestion
	if (src->type != BL_PC && amotion > 1000)
```

File: src/map/clif.cpp (hunk 12 above)
Comment (Lemongrass3110) [inline src/map/clif.cpp:5248]:
```suggestion
	if (battle_config.synchronize_damage && src->type == BL_MOB) {
```
status_get_clientamotion will always return != 0, since you cap it to 1

File: src/map/clif.cpp [hunk 15]
```diff
@@ -5242,6 +5244,12 @@ int clif_damage(struct block_list* src, struct block_list* dst, t_tick tick, int
...
+		// The client only accepts values between 0 and 432; 432 stands for 1x animation speed
```
Comment (Lemongrass3110) [inline src/map/clif.cpp:5249]: Your comment does not make sense to me.
I tried to understand it with the first monster (SCORPION).
AttackMotion 864 (=sdelay) * DEFAULT_ANIMATION_SPEED (=432) / ClientAttackMotion (=384) => 972
But 972 is out of the range of 0-432.

File: doc/mob_db.txt [hunk 16]
```diff
@@ -204,6 +204,19 @@ AttackMotion: Attack animation motion. Low value means monster's attack will be
 
 ---------------------------------------
 
+ClientAttackMotion: The time from the start of a normal attack until the damage frame shows on client. At the same time you also get stopped on the client.
+This value is only needed if you use the "synchronize_damage" feature (battle/client.conf).
+If you created a custom sprite, you want to set this value to the timing of the damage frame in your *.act file.
+
+Background:
+When a clif_damage packet is sent to the client it will also send "sdelay" (AttackMotion) as value.
+The client will ignore all values above 432, and 432 stands for 1.0x animation speed. 216 for example means play the animation at double the speed.
```
Comment (Lemongrass3110) [inline doc/mob_db.txt:213]: I know what you are trying to say, but reading this explanation here gives the impression that I should set ClientAttackMotion to a maximum of 432 and if I want to double its speed I should set it to 216.
But in reality you are talking about something totally different.
Please consider moving this (useful) documentation into clif, as it may be confusing for "normal" users here.

File: conf/battle/client.conf [hunk 17]
```diff
@@ -169,3 +169,10 @@ macro_detection_punishment: 0
 // Amount of time in minutes that the punishment type is active for. Use 0 for infinite.
 // Official: 0
 macro_detection_punishment_time: 0
+
+// Should the damage timing be synchronized between the client and server?
+// This is not official behavior, but it removes the position lag after being hit.
+// This setting only affects normal monster attacks, unless you set "delay_battle_damage" in battle.conf to "no".
```
Comment (Lemongrass3110) [inline conf/battle/client.conf:175]:
```
// Do weapon attacks have a attack speed delay before actual damage is applied? (Note 1)
// NOTE: The official setting is yes, even thought it degrades performance a bit.
delay_battle_damage: yes
```
delay_battle_damage is currently not matching the description, as it affects all attacks and not only "weapon attacks".

**Review by Lemongrass3110 — CHANGES_REQUESTED** [review]

File: src/map/clif.cpp (hunk 12 above)
Comment (Playtester) [reply src/map/clif.cpp:5248]: Should still check for it since we are making a division.

Comment (Playtester) [reply src/map/clif.cpp:5248]: Should still check for it as we divide by it.

File: src/map/clif.cpp (hunk 15 above)
Comment (Playtester) [reply src/map/clif.cpp:5249]: It's fine to send a higher value, it will still just be 1x animation speed.
But maybe I should explain that here.

File: doc/mob_db.txt (hunk 16 above)
Comment (Playtester) [reply doc/mob_db.txt:213]: You want documentation to be in the source file rather than the documentation folder?

File: conf/battle/client.conf (hunk 17 above)
Comment (Playtester) [reply conf/battle/client.conf:175]: Yeah, it was wrong before already. I didn't really touch the functionality of this feature. Should we update the description as part of this PR?

File: src/map/battle.cpp (hunk 13 above)
Comment (Playtester) [reply src/map/battle.cpp:405]: I don't understand this change, doesn't this just remove the whole feature of making sychronize_damage work with delay_battle_damage?

File: src/map/battle.cpp (hunk 14 above)
Comment (Playtester) [reply src/map/battle.cpp:428]: We need to put the if(battle_config.synchronize_damage [...]" part here because otherwise you'd cap amotion to 1000 even if the feature applies.

File: src/map/battle.cpp (hunk 13 above)
Comment (Lemongrass3110) [reply src/map/battle.cpp:405]: Either you want to delay or you want to synchronize. You cannot have both.
If whoever enables your new setting, they want synchronized damage and not delayed damage.
So instead of hiding that we give the new feature priority, we just straight forward go for it.

(And additionally we dont touch the old feature - we may have to find out, when it was broken - or if it has always been for any damage, but outside of the scope of this PR)

File: src/map/clif.cpp (hunk 12 above)
Comment (Lemongrass3110) [reply src/map/clif.cpp:5248]: Then put std::max into the formula, if you want to be safe.
But not checking here for something that cannot happen and hiding the actual reason behind the check (division by zero safeguard vs value not set).

File: src/map/battle.cpp (hunk 14 above)
Comment (Lemongrass3110) [reply src/map/battle.cpp:428]: Everything above 432 (so 1000) will be ignored by the client as you commented.
So everything is fine.

File: src/map/clif.cpp (hunk 12 above)
Comment (Lemongrass3110) [reply src/map/clif.cpp:5248]: std::max

File: doc/mob_db.txt (hunk 16 above)
Comment (Lemongrass3110) [reply doc/mob_db.txt:213]: Well not 100% sure, but since it has nothing to do with "to what should i set that value" I was thinking that may be the better place.

File: conf/battle/client.conf (hunk 17 above)
Comment (Playtester) [reply conf/battle/client.conf:175]: Quick update: I'll rewrite it. Also the new config I move here. So makes more sense when read together.

File: conf/battle/client.conf (hunk 11 above)
Comment (Playtester) [reply conf/battle/client.conf:178]: Originally placed it here because I thought while delay_battle_damage affects more the functionality, the new feature more affects the client display. But considering that both can affect the amotion value and also have some synergy, it makes sense, I'll move it together.

File: src/map/battle.cpp (hunk 13 above)
Comment (Playtester) [reply src/map/battle.cpp:405]: Hmm, but it's important to give the player the option to combine the two settings. Basically battle_sychronize_damage only affects normal skills so of course if you enable this you want normal attacks to be synchronized, which should take priority over the other feature (I'll make it clearer in the description that it takes priority).

At the same time, we want to give the user the choice if they want to delay skill damage (and player damage) or not.

The current implementation from me does not affect the other feature as long as you keep it disabled, so it isn't a problem of backward compatibility.

File: src/map/battle.cpp (hunk 14 above)
Comment (Playtester) [reply src/map/battle.cpp:428]: I think you are missing that the amotion is something completely different from the value we want to send to the client.

Amotion is the time in milliseconds until which the damage shows (here it's only used to create the timer). This isn't limited to 432.

What is (technically) limited to 432 is the what we send to the client, but this is not a value in milliseconds but rather the inverted animation speed.

One monster where this is relevant would be Medusa:
```
    AttackMotion: 1320
    ClientAttackMotion: 1080
```
Here we want amotion in battle.cpp to be 1080.

The value we send to the client would be 432 (or higher), so it plays at 1x speed which results in 1080ms until the damage shows.

File: src/map/clif.cpp (hunk 12 above)
Comment (Playtester) [reply src/map/clif.cpp:5248]: Okay can do that.

Comment (Playtester) [reply src/map/clif.cpp:5248]: Will accept suggestion and add max in next commit.

File: doc/mob_db.txt (hunk 16 above)
Comment (Playtester) [reply doc/mob_db.txt]: I improved the doc to focus on how to set the value rather than how it works internally here.

File: src/map/battle.cpp (hunk 14 above)
Comment (Playtester) [reply src/map/battle.cpp:428]: Actually after sleeping about it, why don't we move the 1000 limit also to the top? Then we can simplify the code as you suggested without breaking the feature.

If I look at the code "amotion" is not used anywhere except the <=1 check and for the timer at the end.

Comment (Playtester) [reply src/map/battle.cpp]: Done!

File: conf/battle/battle.conf [hunk 18]
```diff
@@ -130,10 +130,19 @@ equip_self_break_rate: 100
...
 
-// Do weapon attacks have a attack speed delay before actual damage is applied? (Note 1)
-// NOTE: The official setting is yes, even thought it degrades performance a bit.
+// Should damage have a delay before it is applied? (Note 1)
+// Some skills might not have a delay by default regardless of this setting.
+// The official setting is yes, even thought it degrades performance a bit.
 delay_battle_damage: yes
 
+// Should the damage timing be synchronized between the client and server? (Note 1)
+// This is not official behavior, but it removes the position lag after being hit.
```
Comment (Lemongrass3110) [inline conf/battle/battle.conf:139]:
```suggestion
// This is not official behavior, but it should remove the position lag after being hit by a monster.
```

File: conf/battle/battle.conf [hunk 19]
```diff
@@ -130,10 +130,19 @@ equip_self_break_rate: 100
...
+// This setting only affects normal monster attacks and takes priority over "delay_battle_damage".
+// Many skills show their damage immediately, so setting "delay_battle_damage" to "no" at the same
+// time might improve the experience further, but will not work for all skills.
```
Comment (Lemongrass3110) [inline conf/battle/battle.conf:142]:
```suggestion
// Many skills show their damage immediately, so setting "delay_battle_damage" to "no" at the same
// time might improve the experience further, but will not work for all skills.
```
Could we not add a check for that as well? Maybe in another PR?
Basically we would just have to replace the skill_id == 0 check with a skill_id == 0 || skill_get_delay == 0 (pseudo) check?

**Review by Lemongrass3110 — APPROVED** [review]
Approved with the changes discussed in Discord.

File: conf/battle/battle.conf (hunk 19 above)
Comment (Playtester) [reply conf/battle/battle.conf:142]: The correct way to implement this for skills is to define the clientamotion for each skill and then use this information when sychnronize_damage is enabled. Would be great, but currently we don't have this information available.
