### PR TITLE
Fixes #4034

### LINKED ISSUE #4034: Flag on Vanish bonuses
* **rAthena Hash**: ed83999de439ffd335a301dbf9bb059e047f6bcd
* **Client Date**: -
* **Server Mode**: Both
* **Description of Issue**: 
  * Result: If 2 or more item with bonus bVanishSPx or bVanishHPx with different flag, the triggered flag will be all of them. example 1 item bonus for BF_WEAPON (default bonus without `bf`) then another item using `BF_MAGIC`, it'll be `BF_WEAPON|BF_MAGIC`
  * Expected Result: They work separatedly
  * How to Reproduce:
    1. Create item (better not as weapon, as card maybe) with bonus `bonus2 bSPVanishRate,1000,10;`, means 10% SP vanished each attacking by using weapon `BF_WEAPON` (**should be only** normal attack non-skills `BF_NORMAL|BF_WEAPON`)
    2. Then create item with `bonus3 bSPVanishRate,1000,10,BF_MAGIC;`
    3. Try attack by using skill or not, the SP Vanished will be 20% regardless magic attack or weapon attack
    4. Or in certain order, the BF_MAGIC won't wrok because the force set to BF_WEAPON by bonus2 bSPVanishRate
  * Official Information: -
    * **Additional information** the default weapon flag for SPVanish and HPVanish must be "physical normal attack, non-skill"

* **Modifications that may affect results**: -

```cpp
...
	case SP_SP_VANISH_RATE: // bonus2 bSPVanishRate,x,n;
		if(sd->state.lr_flag != 2) {
			sd->bonus.sp_vanish_rate += type2;
			sd->bonus.sp_vanish_per += val;
			sd->bonus.sp_vanish_flag = BF_WEAPON;
		}
		break;
...
	case SP_SP_VANISH_RATE: // bonus3 bSPVanishRate,x,n,bf;
		if(sd->state.lr_flag != 2) {
			sd->bonus.sp_vanish_rate += type2;
			sd->bonus.sp_vanish_per += type3;
			sd->bonus.sp_vanish_flag |= val;
		}
		break;
```

### PR DESCRIPTION
**Pull request by cydh**
* **Addressed Issue(s)**: #4034

* **Server Mode**: Both

* **Description of Pull Request**: 

  * Move HP/SP Vanish bonuses to vector
  * Corrected the BF flags usage
  * Immaterial Swords, Mental Destroyer, and Dark Priest trigger SPVanish by any attack types

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -6810,17 +6810,30 @@ void battle_vanish_damage(struct map_session_data *sd, struct block_list *target
...
-	int16 vanish_rate_hp = cap_value(sd->bonus.hp_vanish_rate, 0, INT16_MAX);
-	int8 vanish_hp = cap_value(sd->bonus.hp_vanish_per, INT8_MIN, INT8_MAX);
-	// bSPVanishRate
-	int16 vanish_rate_sp = cap_value(sd->bonus.sp_vanish_rate, 0, INT16_MAX);
-	int8 vanish_sp = cap_value(sd->bonus.sp_vanish_per, INT8_MIN, INT8_MAX);
-
-	if (vanish_hp && !(vanish_rate_hp && sd->bonus.hp_vanish_flag & flag && (vanish_rate_hp >= 1000 || rnd() % 1000 < vanish_rate_hp)))
-		vanish_hp = 0;
+	int16 vanish_hp = 0;
+	if (sd->hp_vanish.size()) {
```
Comment (aleos89) [inline src/map/battle.cpp]: I would adjust this to:
```suggestion
	if (!sd->hp_vanish.empty()) {
```

File: src/map/battle.cpp [hunk 2]
```diff
@@ -6810,17 +6810,30 @@ void battle_vanish_damage(struct map_session_data *sd, struct block_list *target
...
+			if (it.rate && (it.rate >= 1000 || rnd() % 1000 < it.rate))
+				vanish_hp += it.per;
+		}
+	}
 
-	if (vanish_sp && !(vanish_rate_sp && sd->bonus.sp_vanish_flag & flag && (vanish_rate_sp >= 1000 || rnd() % 1000 < vanish_rate_sp)))
-		vanish_sp = 0;
+	// bSPVanishRate
+	int16 vanish_sp = 0;
+	if (sd->sp_vanish.size()) {
```
Comment (aleos89) [inline src/map/battle.cpp]: Same as above.

File: src/map/pc.cpp [hunk 3]
```diff
@@ -2759,6 +2759,35 @@ static void pc_bonus_itembonus(std::vector<s_item_bonus> &bonus, uint16 id, int
 	bonus.push_back(entry);
 }
```
Comment (aleos89) [inline src/map/pc.cpp]:
```suggestion
/**
 * Remove HP/SP to player when attacking
 * @param bonus: Bonus array
 * @param rate: Success chance
 * @param per: Percentage of HP/SP to vanish
 * @param flag: Battle flag
 */
```

File: src/map/battle.cpp (hunk 2 above)
Comment (cydh) [reply src/map/battle.cpp]:
```suggestion
	if (!sd->sp_vanish.empty()) {
```

**Comment by cydh** [comment]
Don't confuse the user, we follow the doc/item_bonus.txt, `Trigger criteria (bf)` section
