### PR TITLE
Champion Combo Chaining

### LINKED ISSUE #9293: Champion Combo Chaining Order Incorrect
### rAthena Hash

50146e9

### Client Date

2021-11-03

### Server Mode

Pre-Renewal, Renewal

### Result

You cannot use Tiger Fist after Chain Crush Combo.

You can use Extremity Fist after Tiger Fist.

### Expected Result

You can use Tiger Fist after Chain Crush Combo in pre-renewal, **but not in renewal.**

You cannot use Extremity Fist after Tiger Fist.

### How to Reproduce

Try to use Tiger Fist after Chain Crush Combo.

Try to use Extremity Fist after Tiger Fist.

### Official Information

Confirmed by tests on official server.

For example the following skill order works:

Triple Attack -> Chain Combo -> Combo Finish -> Tiger Fist -> Chain Crush Combo -> Tiger Fist

And it's clearly not possible to use Extremity Fist after Tiger Fist.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9293 

* **Server Mode**: Both

**Description of Pull Request**: 

- Tiger Fist can now be used after Chain Crush Combo in pre-renewal
- Asura Strike (Guillotine Fist) can no longer be used after Tiger Fist
- Combo Finish will no longer delay your auto attack when you don't have enough spheres to combo after it
- Fixes #9293

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -3319,30 +3318,44 @@ void skill_combo(struct block_list* src,struct block_list *dsrc, struct block_li
...
 		case MO_CHAINCOMBO:
-			if (pc_checkskill(sd, MO_COMBOFINISH) > 0 && sd->spiritball > 0) {
+			if (pc_checkskill(sd, MO_COMBOFINISH) > 0 && sd->spiritball >= 1) {
 				duration = 1;
 				target_id = 0; // Will target current auto-target instead
 			}
 			break;
 		case MO_COMBOFINISH:
 			if (sd->status.party_id > 0) //bonus from SG_FRIEND [Komurka]
 				party_skill_check(sd, sd->status.party_id, MO_COMBOFINISH, skill_lv);
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:3328]:
```suggestion
				party_skill_check(sd, sd->status.party_id, skill_id, skill_lv);
```

File: src/map/skill.cpp [hunk 2]
```diff
@@ -18564,7 +18577,13 @@ bool skill_check_condition_castbegin( map_session_data& sd, uint16 skill_id, uin
...
 			break;
 		case CH_TIGERFIST:
-			if(!(sc && sc->getSCE(SC_COMBO) && sc->getSCE(SC_COMBO)->val1 == MO_COMBOFINISH))
+			if (sc == nullptr || sc->getSCE(SC_COMBO) == nullptr)
+				return false;
+			if (sc->getSCE(SC_COMBO)->val1 != MO_COMBOFINISH
+#ifndef RENEWAL
+				&& sc->getSCE(SC_COMBO)->val1 != CH_CHAINCRUSH
+#endif
+			)
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:18586]:
```suggestion
#ifdef RENEWAL
			// In Renewal Tiger Fist can only be used after Combo Finish
			if (sc->getSCE(SC_COMBO)->val1 != MO_COMBOFINISH)
				return false;
#else
			// In Pre-Renewal Tiger Fist can be used after Combo Finish or after Chain Crush Combo
			if (sc->getSCE(SC_COMBO)->val1 != MO_COMBOFINISH && sc->getSCE(SC_COMBO)->val1 != CH_CHAINCRUSH)
				return false;
```

**Review by Lemongrass3110 — APPROVED** [review]
Readability++

Thank you!
