### PR TITLE
Correct Determination of Endure Effect

### LINKED ISSUE #9068: Endure Effect on dmotion=0 units
### rAthena Hash

17f0447

### Client Date

2021-11-03

### Server Mode

Pre-Renewal, Renewal

### Result

Currently we set dmotion to 0 in various situation. Then say we show the "Endure" effect when it is 0.
Even monsters that naturally have dmotion of 0, will show the Endure effect.

### Expected Result

SC_ENDURE but also other situations create a timed "No Damage Motion Possible" effect, which causes dmotion to be 0, prevent stopping and also shows the Endure effect. Monsters that naturally have dmotion of 0 don't have this effect unless granted through other means.

SC_ENDURE (all effects that grant it) is disabled on GVG2/Battleground maps, but other effects granting "No Damage Motion Possible" are not. This is already working but just written here for reference.

Backsliding grants "No Damage Motion Possible" for 200ms.

Firewall hitting an undead creature (including Evil Druid Armor) grant "No Damage Motion Possible" for 2000ms.

NPC_BARRIER grants this effect for 15000ms.
NPC_KEEPING grants this effect for 30000ms.

SC_RUN and similar effects don't actually grant this effect, but still prevent stopping (should probably use "can_escape" similar to NPC_RANDOMMOVE and NPC_RUN).

### How to Reproduce

Use skill that grant endure and test damage against monsters with dmotion 0 (e.g. test dummies in tra_fild).

### Official Information

Atemo confirmed that the dummies in tra_fild don't use the Endure effect.

I confirmed through testing that our logic for the SC_ENDURE-granting effects was already correct.

Other information is available but untested.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9068 

* **Server Mode**: Both

**Description of Pull Request**: 

- Damage motion (dmotion) is no longer set to 0 if the unit has the endure effect
  * This is because even on Endure the dmotion value sent to the client should remain unchanged
- Instead, added a function status_isendure that determines if a unit has the endure effect
  * The function can also return if the unit can be stopped
- Added a new variable endure_tick that contains the time until which a unit cannot be stopped
  * It is not used for everything yet, SC_ENDURE and no_walk_delay are still separate from it
  * When a fire or undead unit is hit by firewall, it now has the endure effect for 2000ms
  * When a unit uses backslide, it now has the endure effect for 200ms if it didn't have it before
  * NPC_BARRIER and NPC_KEEPING also grant endure for their duration (only affects display)
- Damage packet sent to client is now accurate in regards to damage type and dmotion
  * Bosses no longer have infinite endure (but still cannot be stopped in renewal)
  * SC_RUN and SC_WUGDASH also don't grant endure anymore, just prevent stopping
- Moved hardcoded Endure in GVG check to status_disabled.txt
  * Infinite endure from items will no longer be started on the corresponding maps
- Fixes #9068

### CODE REVIEW

File: src/map/clif.cpp [hunk 1]
```diff
@@ -5169,6 +5167,17 @@ static int32 clif_calc_walkdelay( block_list &bl, int32 delay, e_damage_type typ
...
+	// Below are situations that don't send "Endure" to the client, but still prevent being stopped
+	// This includes bosses in renewal (episode 20+) and running / dashing units
+#ifdef RENEWAL
+	if (bl.type == BL_MOB && status_get_class_(&bl) == CLASS_BOSS)
+		return 0;
+#endif
+	status_change* sc = status_get_sc(&bl);
+	if (sc != nullptr && !sc->empty() && (sc->getSCE(SC_RUN) || sc->getSCE(SC_WUGDASH)))
+		return 0;
+
```
Comment (Lemongrass3110) [inline src/map/clif.cpp:5180]: Why is this not part of status_isendure?
And yes I have read the TODO note above.

For me that sounds like status_isendure needs a parameter "visible" true/false.

File: src/map/skill.cpp [hunk 2]
```diff
@@ -10079,6 +10079,11 @@ int32 skill_castend_nodamage_id (struct block_list *src, struct block_list *bl,
 
 	case TF_BACKSLIDING: //This is the correct implementation as per packet logging information. [Skotlex]
 		{
+			// Backsliding makes you immune to being stopped for 200ms, but only if you weren't immune already
+			unit_data* ud = unit_bl2ud(bl);
+			if (ud != nullptr && DIFF_TICK(ud->endure_tick, tick) < 0)
+				ud->endure_tick = tick + 200;
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:10085]: Not really a friend of that DIFF_TICK syntax, would prefer simply using std::max or i64max

File: src/map/status.cpp [hunk 3]
```diff
@@ -9266,6 +9232,36 @@ int32 status_isimmune(struct block_list *bl)
...
+ * @param bl: Object to check [PC|MOB|HOM|MER|ELEM]
+ * @param tick: Current tick
+ * @return Whether object can be stopped (false) or not (true)
+ */
+bool status_isendure(block_list& bl, t_tick tick)
+{
+	// Officially the bonus "no_walk_delay" is actually just SC_ENDURE with unlimited duration
+	// Endure is forbidden on some maps, but we don't apply this on this bonus
+	// That's why we need to check it here
+	if (bl.type == BL_PC && !status_change_isDisabledOnMap(SC_ENDURE, map_getmapdata(bl.m))) {
```
Comment (Lemongrass3110) [inline src/map/status.cpp:9247]:
```suggestion
	if (bl.m >= 0 && bl.type == BL_PC && !status_change_isDisabledOnMap(SC_ENDURE, map_getmapdata(bl.m))) {
```

File: src/map/status.cpp [hunk 4]
```diff
@@ -13331,7 +13327,7 @@ int32 status_change_end( struct block_list* bl, enum sc_type type, int32 tid ){
 			unit_data *ud = unit_bl2ud(bl);
 
 			if (ud)
```
Comment (Lemongrass3110) [inline src/map/status.cpp:13329]:
```suggestion
			if (ud != nullptr) {
```

File: src/map/status.cpp [hunk 5]
```diff
@@ -13331,7 +13327,7 @@ int32 status_change_end( struct block_list* bl, enum sc_type type, int32 tid ){
...
-				ud->attackabletime = ud->canact_tick = ud->canmove_tick = gettick();
+				ud->attackabletime = ud->canact_tick = ud->canmove_tick = ud->endure_tick = gettick();
```
Comment (Lemongrass3110) [inline src/map/status.cpp:13330]:
```suggestion
				ud->attackabletime = ud->canact_tick = ud->canmove_tick = gettick();
				ud->endure_tick = gettick();
			}
```

File: src/map/unit.cpp [hunk 6]
```diff
@@ -3421,7 +3421,8 @@ void unit_dataset(struct block_list *bl)
 	ud->steptimer      = INVALID_TIMER;
 	ud->attackabletime =
 	ud->canact_tick    =
-	ud->canmove_tick   = gettick();
+	ud->canmove_tick   =
```
Comment (Lemongrass3110) [inline src/map/unit.cpp:3424]:
```suggestion
	ud->canmove_tick   = gettick();
```

File: src/map/status.hpp [hunk 7]
```diff
@@ -3619,6 +3619,7 @@ status_change *status_get_sc(struct block_list *bl);
 
 bool status_isdead(block_list &bl);
 int32 status_isimmune(struct block_list *bl);
+bool status_isendure(block_list &bl, t_tick tick);
```
Comment (Lemongrass3110) [inline src/map/status.hpp:3622]:
```suggestion
bool status_isendure(block_list& bl, t_tick tick);
```

File: src/map/status.cpp [hunk 8]
```diff
@@ -10659,7 +10655,7 @@ int32 status_change_start(struct block_list* src, struct block_list* bl,enum sc_
 			unit_data *ud = unit_bl2ud(bl);
 
 			if (ud)
-				ud->attackabletime = ud->canact_tick = ud->canmove_tick = gettick() + tick;
+				ud->attackabletime = ud->canact_tick = ud->canmove_tick = ud->endure_tick = gettick() + tick;
```
Comment (Lemongrass3110) [inline src/map/status.cpp:10658]:
```suggestion
				ud->attackabletime = ud->canact_tick = ud->canmove_tick = gettick() + tick;
				ud->endure_tick = gettick() + tick;
```

File: src/map/battle.cpp [hunk 9]
```diff
@@ -8151,12 +8151,19 @@ struct Damage battle_calc_magic_attack(struct block_list *src,struct block_list
...
+				// Fire and undead units hit by firewall cannot be stopped for 2 seconds
+				if (ud != nullptr)
+					ud->endure_tick = gettick() + 2000;
+				break;
+			}
 			[[fallthrough]];
 		case NJ_KAENSIN:
 		case PR_SANCTUARY:
-			ad.dmotion = 1; //No flinch animation.
+			// TODO: This code is a temporary workaround because right now we stop monsters for their dmotion which is not official
```
[the remark this answers is not in the document]
Comment (Playtester) [reply src/map/battle.cpp:8165]: It's a general workaround, I guess. But it's mainly to get monsters "use up" the firewall faster. This will be removed once I'm done with the walk delay rework.

File: src/map/skill.cpp (hunk 2 above)
Comment (Playtester) [reply src/map/skill.cpp:10085]: I think we should consistently use DIFF_TICK mainly because then we can easily do adjustments that should affect all t_tick comparisons.

File: src/map/status.cpp (hunk 8 above)
Comment (Playtester) [reply src/map/status.cpp:10658]: Why?

File: db/status_disabled.txt [hunk 10]
```diff
@@ -25,10 +25,14 @@
 // Example:
 // SC_ENDURE,4   // Endure status will be removed when the player enters GvG and WoE Castle maps; Also cannot be inflicted again.
 
+//----------------------------------------------------------------------------
+// Disabled/Removed on all WoE maps and battlegrounds
```
[the remark this answers is not in the document]
Comment (Playtester) [reply db/status_disabled.txt:29]: We used the term "WoE:TE Castles" below so I wanted to be consistent. GVG might mislead into thinking WoE TE maps are not included.

File: src/map/unit.cpp (hunk 6 above)
Comment (Playtester) [reply src/map/unit.cpp:3424]: If you go this far I would also remove the extra spaces.

File: src/map/status.hpp (hunk 7 above)
Comment (Playtester) [reply src/map/status.hpp:3622]: Saw that the other status_is function use it like that and thought it looks better. You prefer it next to the type rather than the object name?

File: db/status_disabled.txt (hunk 10 above)
[the remark this answers is not in the document]
Comment (Playtester) [reply db/status_disabled.txt:29]: No they don't, the "16" within the 28 stands for WoE:TE castles.

[the remark this answers is not in the document]
Comment (Daegaladh) [reply db/status_disabled.txt:29]: Ah right, makes sense, then maybe specify (GVG + WoE:TE) ?

File: src/map/clif.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/clif.cpp]: Updated, please check.

File: src/map/status.cpp [hunk 11]
```diff
@@ -9266,6 +9232,49 @@ int32 status_isimmune(struct block_list *bl)
...
+ * @param tick: Current tick
+ * @param visible: If true, function returns if the endure effect should be shown on the client
+ * @return Whether object can be stopped (false) or not (true)
+ */
+bool status_isendure(block_list& bl, t_tick tick, bool visible)
+{
+	// Officially the bonus "no_walk_delay" is actually just SC_ENDURE with unlimited duration
+	// Endure is forbidden on some maps, but we don't apply this on this bonus
+	// That's why we need to check it here
+	if (bl.m >= 0 && bl.type == BL_PC && !status_change_isDisabledOnMap(SC_ENDURE, map_getmapdata(bl.m))) {
```
Comment (Lemongrass3110) [inline src/map/status.cpp:9248]: Is it okay to ignore status_change_isDisabledOnMap for other BL types?
In status_change_start we check it independent of BL type.

File: src/map/status.cpp [hunk 12]
```diff
@@ -9266,6 +9232,49 @@ int32 status_isimmune(struct block_list *bl)
...
+		if (reinterpret_cast<map_session_data&>(bl).special_state.no_walk_delay)
+			return true;
+	}
+
+	unit_data* ud = unit_bl2ud(&bl);
+	if (ud != nullptr && DIFF_TICK(ud->endure_tick, tick) > 0)
+		return true;
+
+	status_change* sc = status_get_sc(&bl);
+	if (sc != nullptr && !sc->empty()) {
```
Comment (Lemongrass3110) [inline src/map/status.cpp:9258]:
```suggestion
	if (status_change* sc = status_get_sc(&bl); sc != nullptr && !sc->empty()) {
```

File: src/map/status.cpp [hunk 13]
```diff
@@ -9266,6 +9232,49 @@ int32 status_isimmune(struct block_list *bl)
...
+	// Officially the bonus "no_walk_delay" is actually just SC_ENDURE with unlimited duration
+	// Endure is forbidden on some maps, but we don't apply this on this bonus
+	// That's why we need to check it here
+	if (bl.m >= 0 && bl.type == BL_PC && !status_change_isDisabledOnMap(SC_ENDURE, map_getmapdata(bl.m))) {
+		if (reinterpret_cast<map_session_data&>(bl).special_state.no_walk_delay)
+			return true;
+	}
+
+	unit_data* ud = unit_bl2ud(&bl);
+	if (ud != nullptr && DIFF_TICK(ud->endure_tick, tick) > 0)
```
Comment (Lemongrass3110) [inline src/map/status.cpp:9254]:
```suggestion
	if (unit_data* ud = unit_bl2ud(&bl); ud != nullptr && DIFF_TICK(ud->endure_tick, tick) > 0)
```

File: src/map/status.cpp [hunk 14]
```diff
@@ -9266,6 +9232,49 @@ int32 status_isimmune(struct block_list *bl)
...
+		if (sc->getSCE(SC_ENDURE))
+			return true;
+
+		// These status changes don't send "Endure" to the client, but still prevent being stopped
+		if (!visible && (sc->getSCE(SC_RUN) || sc->getSCE(SC_WUGDASH)))
+			return true;
+	}
+
+	// Bosses in renewal (episode 20+) cannot be stopped by damage, but still show damage normally
+#ifdef RENEWAL
```
Comment (Lemongrass3110) [inline src/map/status.cpp:9270]:
```suggestion
#ifdef RENEWAL
	// Bosses in renewal (episode 20+) cannot be stopped by damage, but still show damage normally
```

File: src/map/status.cpp (hunk 8 above)
Comment (Lemongrass3110) [reply src/map/status.cpp:10671]: Track changes / git blame.
If you want something like this, please define a variable above and asign it to all.

File: src/map/status.cpp (hunk 4 above)
Comment (Lemongrass3110) [reply src/map/status.cpp:13342]: Here you touched the line.

File: src/map/unit.cpp (hunk 6 above)
Comment (Lemongrass3110) [reply src/map/unit.cpp:3424]: Track changes / git blame.
If you want something like this, please define a variable above and asign it to all.

Feel free to remove the useless extra spacing.

File: src/map/status.cpp (hunk 5 above)
Comment (Lemongrass3110) [reply src/map/status.cpp:13343]: Track changes / git blame.
If you want something like this, please define a variable above and asign it to all.

File: src/map/skill.cpp (hunk 2 above)
Comment (Lemongrass3110) [reply src/map/skill.cpp:10084]: I think i dont really understand your explanation.
But if i understand you correctly, then we should introduce a utility function that does this.

File: src/map/status.cpp (hunk 11 above)
Comment (Playtester) [reply src/map/status.cpp:9248]: special_state.no_walk_delay only applies to BL_PC

The restriction itself applies to all BL types of course, but it's not relevant here.

File: src/map/status.cpp (hunk 4 above)
Comment (Playtester) [reply src/map/status.cpp:13342]: I didn't. It's white.

Comment (Lemongrass3110) [reply src/map/status.cpp:13340]: Ah yeah I suggested it here, because I had to suggest a { for the changes below.

**Review by Atemo — APPROVED** [review]
It looks good to me

File: src/map/status.cpp [hunk 15]
```diff
@@ -9266,6 +9232,47 @@ int32 status_isimmune(struct block_list *bl)
...
+			return true;
+	}
+
+	if (unit_data* ud = unit_bl2ud(&bl); ud != nullptr && DIFF_TICK(ud->endure_tick, tick) > 0)
+		return true;
+
+	if (status_change* sc = status_get_sc(&bl); sc != nullptr && !sc->empty()) {
+		// Officially endure also sets endure_tick
+		// However, we have a lot of extra logic for infinite endure, so we use the status change for now
+		if (sc->getSCE(SC_ENDURE))
```
Comment (Lemongrass3110) [inline src/map/status.cpp:9259]:
```suggestion
		if (sc->getSCE(SC_ENDURE) != nullptr)
```

File: src/map/status.cpp [hunk 16]
```diff
@@ -9266,6 +9232,47 @@ int32 status_isimmune(struct block_list *bl)
...
+			return true;
+
+		// These status changes don't send "Endure" to the client, but still prevent being stopped
+		if (!visible && (sc->getSCE(SC_RUN) || sc->getSCE(SC_WUGDASH)))
```
Comment (Lemongrass3110) [inline src/map/status.cpp:9263]:
```suggestion
		if (!visible && (sc->getSCE(SC_RUN) != nullptr || sc->getSCE(SC_WUGDASH) != nullptr))
```

File: src/map/status.cpp [hunk 17]
```diff
@@ -9266,6 +9232,47 @@ int32 status_isimmune(struct block_list *bl)
...
+ * @param bl: Object to check [PC|MOB|HOM|MER|ELEM]
+ * @param tick: Current tick
+ * @param visible: If true, function returns if the endure effect should be shown on the client
+ * @return Whether object can be stopped (false) or not (true)
+ */
+bool status_isendure(block_list& bl, t_tick tick, bool visible)
+{
+	// Officially the bonus "no_walk_delay" is actually just SC_ENDURE with unlimited duration
+	// Endure is forbidden on some maps, but we don't apply this on this bonus
+	// That's why we need to check it here
```
Comment (Lemongrass3110) [inline src/map/status.cpp:9247]:
```suggestion
	// Officially the bonus "no_walk_delay" is actually just SC_ENDURE with unlimited duration.
	// Endure is forbidden on some maps, but we still allow the bonus on such maps.
	// That's why we need to check it here and ignore the bonus on such maps to correctly mimic official behavior.
```

**Review by Lemongrass3110 — APPROVED** [review]
