### PR TITLE
Venom Splasher, Venom Knife

### LINKED ISSUE #8221: Venom Splasher should consider weapon element
### rAthena Hash

8745391

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

Venom Splasher ignores the weapon element.

### Relevant Log Output

_No response_

### Expected Result

Venom Splasher does not ignore the weapon element.
It's also Poison element only when you used Enchant Poison on yourself.
It does not consider attack card modifiers however. Even racial cards are not considered.

### How to Reproduce

Use Venom Splasher.
Cast Enchant Poison and use Venom Splasher again on an enemy that takes more or less damage from Poison.
Use Elemental Weapon (e.g. Katar of Quaking) and use Venom Splasher on an enemy that takes no damage from Earth.

### Official Information

Assassin Cross 94/69, 99 DEX, All Masteries except Advanced Katar Mastery:

vs. Martin
Main Gauche - 46
Main Gauche + Splasher 1 - 464
VVVS + Splasher 1 - 504
VVVS + Enchant Poison 6 + Splasher 1 - 620
VVVS + Enchant Poison 6 + EDP 5 + Splasher 1 - 620

4x Underneath MG - 82
4x Underneath MG + Splasher 1 - 464
4x Underneath MG + Enchant Poison 6 + Splasher 1 - 580
4x Clamorous MG - 82
4x Clamorous MG + Splasher 1 - 464
4x Clamorous MG + Enchant Poison 6 + Splasher 1 - 580

Enchant Poison 6 + Splasher 1 vs. Verit - MISS
Katar of Quaking + Splasher 1 vs. Verit - 889
Katar of Quaking + Splasher 1 vs. Mandragora - MISS

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #8221

* **Server Mode**: Both (some things were already working on renewal)

**Description of Pull Request**: 
 
- Venom Splasher now ignores +% damage cards, but no longer ignores weapon element
- Venom Splasher now uses the correct durations and cooldowns in pre-re (was already correct in renewal)
- Both skills now correctly use default poison duration
- Venom Splasher and Venom Knife now have a poison chance of 100%
- Fixes #8221

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -1422,15 +1422,13 @@ int skill_additional_effect( struct block_list* src, struct block_list *bl, uint
...
 	case AS_SPLASHER:
-		if(!sc_start2(src,bl,SC_POISON,(4*skill_lv+10),skill_lv,src->id,skill_get_time2(skill_id,skill_lv))
-			&& sd && skill_id==TF_POISON
-		)
-			clif_skill_fail(sd,skill_id,USESKILL_FAIL_LEVEL,0);
+		sc_start2(src, bl, SC_POISON, 100, skill_lv, src->id, skill_get_time2(skill_id, skill_lv));
+		break;
+
+	case TF_POISON:
+		if (!sc_start2(src, bl, SC_POISON, (4 * skill_lv + 10), skill_lv, src->id, skill_get_time2(skill_id, skill_lv)) && sd)
```
Comment (aleos89) [inline src/map/skill.cpp:1430]:
```suggestion
		if (sd && !sc_start2(src, bl, SC_POISON, (4 * skill_lv + 10), skill_lv, src->id, skill_get_time2(skill_id, skill_lv)))
```
Slight speed-up.

**Review by aleos89 — APPROVED** [review]

File: src/map/skill.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/skill.cpp:1430]: This would break it for monsters.
