### PR TITLE
Fixed Max HP & SP rate bonus

### LINKED ISSUE #4264: HP bonuses formula incorrect for pre-Renewal
* **rAthena Hash**: Latest

* **Client Date**: 2017-06-14

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  In a similar fashion to the Heal formula, the HP bonuses formula is also wrong for pre-RE. In 96443cd71073ad752c65d4d6705a61ec1747735f some changes were made which resulted in a combination such as Tao Gunka with Berserk/Frenzy not working correctly anymore. On rAthena, it applies one of them on the Base HP only.

As reported by one of our players, Base HP = 10969. With only Berserk = 32907. With only Tao Gunka = 21938. With both = 43878. This should be 65814.

We confirmed this on our 11.3 Aegis server. Base HP was 10670. With Berserk = 32010. With only Tao Gunka = 21340. With both = 64020.
  * Expected Result: Berserk applies to HP including bonuses, not on base.
  * How to Reproduce:  Test Tao Gunka + Berserk/Frenzy on Pre-Renewal Aegis.
  * Official Information: Aegis 11.3.
  

* **Modifications that may affect results**:

### PR DESCRIPTION
**Pull request by cydh**
* **Addressed Issue(s)**: #4264

* **Server Mode**: Both

* **Description of Pull Request**: 
  - Just trying to fix #4264

### CODE REVIEW

File: src/map/status.cpp [hunk 1]
```diff
@@ -1147,6 +1147,8 @@ void initChangeTables(void)
 	StatusIconChangeTable[SC_SPL_MATK] = EFST_SPL_MATK;
 	StatusIconChangeTable[SC_ATKPOTION] = EFST_PLUSATTACKPOWER;
 	StatusIconChangeTable[SC_MATKPOTION] = EFST_PLUSMAGICPOWER;
+	StatusIconChangeTable[SC_INCREASE_MAXHP] |= EFST_ATKER_ASPD;
```
Comment (Daegaladh) [inline src/map/status.cpp:1150]: `|=` copypaste fail

File: src/map/status.cpp [hunk 2]
```diff
@@ -1147,6 +1147,8 @@ void initChangeTables(void)
...
+	StatusIconChangeTable[SC_INCREASE_MAXSP] |= EFST_ATKER_MOVESPEED;
```
Comment (Daegaladh) [inline src/map/status.cpp:1151]: `|=` copypaste fail

Comment (Daegaladh) [reply src/map/status.cpp:1151]: Also Gold Pills SCs are wrong on pre-re item_db
