### PR TITLE
Fixes SCB calculations

### LINKED ISSUE #6715: SC_ on healer not working properly
* **rAthena Hash**: https://github.com/rathena/rathena/commit/5193fd6c92bac2d2db3cb88e128e5c404389980d

* **Client Date**: 20211103

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  SC_ on healer not working properly
  * Expected Result:  SC_ on healer working including when other skills on player are used
  * How to Reproduce: 
  
Use buff like this

sc_start SC_BLESSING,360000,10;
sc_start SC_INCREASEAGI,360000,10;
sc_start SC_IMPOSITIO,360000,5;
sc_start SC_SUFFRAGIUM,360000,3;
sc_start SC_KYRIE,360000,10;
sc_start SC_MAGNIFICAT,360000,5;
sc_start SC_GLORIA,360000,5;
sc_start SC_ANGELUS,360000,10;

and maybe another SC_

then use skill (one below)

SO_DIAMONDDUST
SO_PSYCHIC_WAVE
SO_VARETYR_SPEAR

and maybe another SO skill

and after that will happen 

all buffs contained in sc_start will disappear, can be seen in the status window (status will decrease, even the way back to normal like without using increase agi and another sc on healer). but status icon remains but all effects (check on status window and test walking) of sc_start disappear. 

  
  * Official Information: 
  

* **Modifications that may affect results**:

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #6715

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Follow up to d739e8f.
  * Resolves issues with status calculations getting improperly checked.
Thanks to @mazvi, @kaninhot004, and @Rayvakarian!

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -12635,7 +12635,7 @@ TIMER_FUNC(skill_castend_id){
 		if( sd && ud->skilltimer != INVALID_TIMER && (pc_checkskill(sd,SA_FREECAST) > 0 || ud->skill_id == LG_EXEEDBREAK) )
 		{// restore original walk speed
 			ud->skilltimer = INVALID_TIMER;
-			status_calc_bl(&sd->bl, SCB_SPEED|SCB_ASPD);
+			status_calc_bl(&sd->bl, { SCB_SPEED , SCB_ASPD });
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:12638]:
```suggestion
			status_calc_bl(&sd->bl, { SCB_SPEED, SCB_ASPD });
```

File: src/map/skill.cpp [hunk 2]
```diff
@@ -12965,7 +12965,7 @@ TIMER_FUNC(skill_castend_pos){
 	if( sd && ud->skilltimer != INVALID_TIMER && ( pc_checkskill(sd,SA_FREECAST) > 0 || ud->skill_id == LG_EXEEDBREAK ) )
 	{// restore original walk speed
 		ud->skilltimer = INVALID_TIMER;
-		status_calc_bl(&sd->bl, SCB_SPEED|SCB_ASPD);
+		status_calc_bl(&sd->bl, { SCB_SPEED , SCB_ASPD });
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:12968]:
```suggestion
		status_calc_bl(&sd->bl, { SCB_SPEED, SCB_ASPD });
```

File: src/map/unit.cpp [hunk 3]
```diff
@@ -2064,7 +2064,7 @@ int unit_skilluse_id2(struct block_list *src, int target_id, uint16 skill_id, ui
 		ud->skilltimer = add_timer( tick+casttime, skill_castend_id, src->id, 0 );
 
 		if( sd && (pc_checkskill(sd,SA_FREECAST) > 0 || skill_id == LG_EXEEDBREAK) )
-			status_calc_bl(&sd->bl, SCB_SPEED|SCB_ASPD);
+			status_calc_bl(&sd->bl, { SCB_SPEED , SCB_ASPD });
```
Comment (Lemongrass3110) [inline src/map/unit.cpp:2067]:
```suggestion
			status_calc_bl(&sd->bl, { SCB_SPEED, SCB_ASPD });
```

File: src/map/unit.cpp [hunk 4]
```diff
@@ -2256,7 +2256,7 @@ int unit_skilluse_pos2( struct block_list *src, short skill_x, short skill_y, ui
 		ud->skilltimer = add_timer( tick+casttime, skill_castend_pos, src->id, 0 );
 
 		if( (sd && pc_checkskill(sd,SA_FREECAST) > 0) || skill_id == LG_EXEEDBREAK)
-			status_calc_bl(&sd->bl, SCB_SPEED|SCB_ASPD);
+			status_calc_bl(&sd->bl, { SCB_SPEED , SCB_ASPD });
```
Comment (Lemongrass3110) [inline src/map/unit.cpp:2259]:
```suggestion
			status_calc_bl(&sd->bl, { SCB_SPEED, SCB_ASPD });
```

File: src/map/unit.cpp [hunk 5]
```diff
@@ -2912,7 +2912,7 @@ int unit_skillcastcancel(struct block_list *bl, char type)
 	ud->skilltimer = INVALID_TIMER;
 
 	if( sd && (pc_checkskill(sd,SA_FREECAST) > 0 || skill_id == LG_EXEEDBREAK) )
-		status_calc_bl(&sd->bl, SCB_SPEED|SCB_ASPD);
+		status_calc_bl(&sd->bl, { SCB_SPEED , SCB_ASPD });
```
Comment (Lemongrass3110) [inline src/map/unit.cpp:2915]:
```suggestion
		status_calc_bl(&sd->bl, { SCB_SPEED, SCB_ASPD });
```

**Review by Lemongrass3110 — APPROVED** [review]
