### PR TITLE
Fixes script command rentalcountitem

### LINKED ISSUE #7121: rentalcountitem is triggered by non-rental items
* **rAthena Hash**: 6d07a43

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Non-rental items are detected by the script command rentalcountitem.
  * Result: Non-rental items are being detected by rentalcountitem.
  * Expected Result:  Non-rental items shouldn't be detected by the script command rentalcountitem.
  * How to Reproduce: https://pastebin.com/KYNivGyn

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #7121

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Fixes an issue with normal items getting mixed into the rental count.
Thanks to @Cukinaru!

### CODE REVIEW

File: src/map/script.cpp [hunk 1]
```diff
@@ -7082,7 +7082,8 @@ static int script_countitem_sub(struct item *items, std::shared_ptr<item_data> i
 					continue;
 			}
 
-			count += items[i].amount;
+			if ((rental && itm->expire_time > 0) || (!rental && itm->expire_time == 0))
```
Comment (Lemongrass3110) [inline src/map/script.cpp:7085]: Maybe move it up, because these checks allow failing faster.

**Review by Lemongrass3110 — APPROVED** [review]
