### PR TITLE
Fixes Reading Spellbook behavior

### LINKED ISSUE #6705: Reading Spell Book and Comet not working properly
* **rAthena Hash**: 

* **Client Date**:  20210107

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  Reading Spell Book sometimes cannot be casted and or cannot use any book for that matter especially above 3 spells. 
  Additional: Comet For some reason doesn't use the Magic Poison Status effect even if it is indicated on Status DB and was instead using burn.
  * Expected Result:  You can do the things above
  * How to Reproduce:  Use reading spell book Issue started after the Status Change DB update
  * Official Information: 
  

* **Modifications that may affect results**:

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #6705

* **Server Mode**: Renewal

* **Description of Pull Request**:
  * Confirmed on kRO that Reading Spellbook persists through relog but not death.
  * Comet should now give the target Magic Poison instead of Burning.
Thanks to @Relliksuriv!

### CODE REVIEW

**Review by Lemongrass3110 — APPROVED** [review]

File: src/map/skill.cpp [hunk 1]
```diff
@@ -21941,19 +21941,19 @@ int skill_magicdecoy(struct map_session_data *sd, t_itemid nameid) {
  * @param sd: Player data
  * @param nameid: Spellbook item used
  */
-void skill_spellbook(struct map_session_data *sd, t_itemid nameid) {
-	nullpo_retv(sd);
+void skill_spellbook(map_session_data &sd, t_itemid nameid) {
+	nullpo_retv(&sd);
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:21945]:
```suggestion
```
NO!
