### PR TITLE
Earth Drive Animation

### LINKED ISSUE #9349: Earth Drive packets
### rAthena Hash

10bbf25

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Earth Drive is not showing an animation on more recent clients.

### Expected Result

Earth Drive is showing an animation on more recent clients.

### How to Reproduce

Use Earth Drive.

### Official Information

Packet captures:

HEADER_ZC_USESKILL_ACK2
{
"Aid": 999999,
"Targetid": 999999,
"Xpos": 0,
"Ypos": 0,
"Skid": 2323,
"Property": 2,
"Delaytime": 342,
"Isdisposable": false,
"Command": 2043
}

540ms later (= Attack Motion)

HEADER_ZC_NOTIFY_SKILL2
{
"Skid": 2323,
"Aid": 999999,
"Targetid": 999999,
"Starttime": 453042566,
"Attackmt": 540,
"Attackedmt": 0,
"Damage": -30000,
"Level": 5,
"Count": 1,
"Action": 6,
"Command": 478
}

0ms later

HEADER_ZC_NOTIFY_SKILL2
{
"Skid": 2323,
"Aid": 999999,
"Targetid": 27777,
"Starttime": 453042566,
"Attackmt": 540,
"Attackedmt": 480,
"Damage": 19055,
"Level": 5,
"Count": 5,
"Action": 8,
"Command": 478
}

0ms later

HEADER_ZC_USE_SKILL2
{
"Skid": 2323,
"Amount": 5,
"Targetaid": 999999,
"Srcaid": 999999,
"Result": true,
"Command": 2507
}

You can see that it sends both packets. They just added the new one at the end.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9349 

* **Server Mode**: Renewal

**Description of Pull Request**: 

- Fixed Earth Drive not showing its animation ever since it was redefined as a nodamage skill
- Removed obsolete code for Earth Drive as a unit / damage skill
- Fixes #9349

Special thanks to LadyNanuia

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -14464,7 +14464,6 @@ int32 skill_castend_pos2(struct block_list* src, int32 x, int32 y, uint16 skill_
 		case MO_BODYRELOCATION:
 		case CR_CULTIVATION:
 		case HW_GANBANTEIN:
-		case LG_EARTHDRIVE:
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:14467]: If you remove it here, will it not send clif_skill_poseffect?

**Review by Lemongrass3110 — APPROVED** [review]

File: src/map/skill.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/skill.cpp:14467]: > If you remove it here, will it not send clif_skill_poseffect?

It will not reach this code anymore as it's no longer a unit skill.
