### PR TITLE
Musical Strike Pre-Re Damage

### LINKED ISSUE #9576: Musical Strike / Throw Arrow Pre-Re Damage
### rAthena Hash

636f33d

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

Musical Strike / Throw Arrow deals `125% + 25%*level` damage.

### Expected Result

Musical Strike / Throw Arrow deals `60% + 40%*level` damage.

### How to Reproduce

Use Musical Strike / Throw Arrow and test damage.

### Official Information

https://ro.kokotewa.com/db/skl_info?id=BA_MUSICALSTRIKE
https://ro.kokotewa.com/db/skl_info?id=DC_THROWARROW

Verified by test:

Minstrel 94/69, All Stats+50, Violin, Owl's Eye 10, Musical Lesson 3

vs. Barricade
Musical Strike 1 - 191 damage
Musical Strike 2 - 264 damage
Musical Strike 3 - 337 damage

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9576

* **Server Mode**: Pre-Renewal

**Description of Pull Request**: 

- Fixed damage of Musical Strike and Throw Arrow in pre-re
- Fixes #9576

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -4921,7 +4921,7 @@ static int32 battle_calc_attack_skill_ratio(struct Damage* wd, block_list *src,b
 #ifdef RENEWAL
 			skillratio += 10 + 40 * skill_lv;
 #else
-			skillratio += 25 + 25 * skill_lv;
+			skillratio += -40 + 40 * skill_lv;
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:4924]: Isnt this assuming that skillratio is 100 at the time of the calculation?

From how I understood it, wouldnt it be better like:

skillratio = skillratio * 60 / 100;
skillratio += 40 * skill_lv;

Comment (Playtester) [reply src/map/battle.cpp:4924]: We always do it this way, because that's how it stacks. For example a skill with 500% if you have a 100% skillratio increase, it becomes 600% and not 1000%.
