### PR TITLE
Fixes SQL mob database parsing

### LINKED ISSUE #6787: src/c4/yml/tree.cpp:1583: check failed: ( is map(node)) error on latest commit
* **rAthena Hash**:  b3343df2ab31cc3ea331fdbce6d26e8133d14daf

* **Server Mode**:  pre-re but most likely renewal aswell

* **Description of Issue**: map-server crash using SQL mode on Ubuntu 21.10
  * How to Reproduce: on Ubuntu 21.10 put server into SQL mode, compile and upon startup it crashes map-server. crash dump is attached.
[crash dump.txt](https://github.com/rathena/rathena/files/8403406/crash.dump.txt)

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #6787

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Resolves the SQL monster database not being properly parsed into YAML nodes.
  * Also resolves the skill database improperly reporting issues.
Thanks to @L4M3573R and @Lemongrass3110!

### CODE REVIEW

File: src/map/mob.cpp [hunk 1]
```diff
@@ -5101,36 +5108,54 @@ static bool mob_read_sqldb_sub(std::vector<std::string> str) {
...
+	ryml::NodeRef mvpDropsNode = node["MvpDrops"];
+	bool mvpheader = false;
+
 	for (uint8 i = 0; i < MAX_MVP_DROP; i++) {
-		ryml::NodeRef mvpDropsNode = node["MvpDrops"];
-		mvpDropsNode |= ryml::SEQ;
-		
+		if (!mvpheader) {
+			mvpDropsNode |= ryml::SEQ;
+			mvpheader = false;
```
Comment (Lemongrass3110) [inline src/map/mob.cpp:5117]:
```suggestion
			mvpheader = true;
```

**Review by Lemongrass3110 — APPROVED** [review]

File: src/map/mob.cpp [hunk 2]
```diff
@@ -5016,11 +5017,17 @@ static bool mob_read_sqldb_sub(std::vector<std::string> str) {
 	if (!str[++index].empty() && strcmp(str[index].c_str(), "Formless") != 0)
 		node["Race"] << str[index];
 
+	ryml::NodeRef raceGroupsNode = node["RaceGroups"];
+	bool header = false;
```
Comment (aleos89) [inline src/map/mob.cpp:5021]:
```suggestion
	bool groupheader = false;
```

File: src/map/mob.cpp [hunk 3]
```diff
@@ -5016,11 +5017,17 @@ static bool mob_read_sqldb_sub(std::vector<std::string> str) {
...
+
 	for (uint16 i = 1; i < RC2_MAX; i++) {
 		if (!str[i + index].empty()) {
-			auto raceGroupsNode = node["RaceGroups"];
-			raceGroupsNode |= ryml::MAP;
-			node["RaceGroups"][c4::to_csubstr(script_get_constant_str("RC2_", i) + 4)] << (std::stoi(str[i + index]) ? "true" : "false");
+			if (!header) {
```
Comment (aleos89) [inline src/map/mob.cpp:5025]:
```suggestion
			if (!groupheader) {
```

File: src/map/mob.cpp [hunk 4]
```diff
@@ -5016,11 +5017,17 @@ static bool mob_read_sqldb_sub(std::vector<std::string> str) {
...
+				raceGroupsNode |= ryml::MAP;
+				header = true;
```
Comment (aleos89) [inline src/map/mob.cpp:5027]:
```suggestion
				groupheader = true;
```
