### PR TITLE
Fixes Overheat behavior

### LINKED ISSUE #5395: Madogear Overheating issue.
* **rAthena Hash**: 

* **Client Date**: 

 20200304

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  Mechanic (Madogear) Overheat counter doesnt exist. meaning they will never oveheat
  * Expected Result:  The Madogear counter as added in the class update https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/ , to show you how far away from overheating you are.
  * How to Reproduce:  Equip mado suit and tank monsters.
  * Official Information:
https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/ "added mado gear overheating counter", but not only is this not the case on rA, it also doesnt overheat at all it seems.
  

* **Modifications that may affect results**:

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #5395

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Fixes Overheat not properly accounting for the Mechanic during battle calculations.
  * Minor cleanups and improvements.
Thanks to @LotusRO!

### CODE REVIEW

File: src/map/pc.cpp [hunk 1]
```diff
@@ -11503,14 +11503,14 @@ bool pc_setstand(struct map_session_data *sd, bool force){
...
-	uint16 skill_lv;
-
 	nullpo_retv(sd);
 
-	skill_lv = cap_value(pc_checkskill(sd, NC_MAINFRAME), 0, 4);
-	if ((sce = sd->sc.data[SC_OVERHEAT_LIMITPOINT])) {
+	status_change_entry *sce = sd->sc.data[SC_OVERHEAT_LIMITPOINT];
+
+	if (sce) {
+		int16 limit[] = { 150, 200, 280, 360, 450 };
```
Comment (Lemongrass3110) [inline src/map/pc.cpp:11511]:
```suggestion
		static std::vector<int16> limit = { 150, 200, 280, 360, 450 };
```

File: src/map/pc.cpp [hunk 2]
```diff
@@ -11503,14 +11503,14 @@ bool pc_setstand(struct map_session_data *sd, bool force){
...
+		uint16 skill_lv = cap_value(pc_checkskill(sd, NC_MAINFRAME), 0, 4);
```
Comment (Lemongrass3110) [inline src/map/pc.cpp:11512]:
```suggestion
		uint16 skill_lv = cap_value(pc_checkskill(sd, NC_MAINFRAME), 0, limit.size()-1);
```

File: src/map/status.cpp [hunk 3]
```diff
@@ -14483,7 +14483,7 @@ TIMER_FUNC(status_change_timer){
 	case SC_OVERHEAT_LIMITPOINT:
 		if (--(sce->val1) >= 0) { // Cooling
 			int16 limit[] = { 150, 200, 280, 360, 450 };
```
Comment (Lemongrass3110) [inline src/map/status.cpp:14485]:
```suggestion
			static std::vector<int16> limit = { 150, 200, 280, 360, 450 };
```

File: src/map/status.cpp [hunk 4]
```diff
@@ -14483,7 +14483,7 @@ TIMER_FUNC(status_change_timer){
...
-			uint16 skill_lv = (sd ? pc_checkskill(sd, NC_MAINFRAME) : 0);
+			uint16 skill_lv = (sd ? cap_value(pc_checkskill(sd, NC_MAINFRAME), 0, 4) : 0);
```
Comment (Lemongrass3110) [inline src/map/status.cpp:14486]:
```suggestion
			uint16 skill_lv = (sd ? cap_value(pc_checkskill(sd, NC_MAINFRAME), 0, limit.size()-1) : 0);
```

**Review by Lemongrass3110 — APPROVED** [review]
