### PR TITLE
Cannon Ball Skills (P.ATK and Res)

### LINKED ISSUE #8380: PATK/Res Effect on Cart Cannon / Arm Cannon
### rAthena Hash

924d1dd

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

PATK affects Cart Cannon's "Cannon Ball" ATK.

RES affects Cart Cannon.

### Relevant Log Output

_No response_

### Expected Result

PATK does not affect Cart Cannon's "Cannon Ball" ATK.

RES does not affect Cart Cannon.

### How to Reproduce

Use Cart Cannon with a character that has PATK against a character that has RES with only a Cannon Ball equipped. Compare damage.

### Official Information

grafik
Biolo 250/55
Cannon Ball -> Item ID 18004
Cart Boost 5
Cart Cannon 5

vs. Inquisitor 250/51
grafik
Damage: 114523

Damage vs. Dummy (21064): 114667

Normal Attack Ungeared -> 2096
With Cart Boost 5 -> 2146

With Weapon -> Item ID 590047

Normal Attack Crit -> 4391
With Cart Boost 5 -> 4479

Note: The previous tests on Guillotine Fist also show that Res is ignored: https://github.com/rathena/rathena/issues/8363
It is probably that all skills that use the "Simple Defense" formula also ignore Res. But this requires more tests and should be done in a separate PR, so I removed it from the scope.

The 250 ATK from Cannon Ball is apparently treated like MasteryATK rather than EquipATK. At first I thought EquipATK is not affected by PATK in general, but these countertests proof that EquipATK IS affected:
grafik
Regular Bow Critical Hits vs Dummy (21065):
Arrow - 3097
Iron Arrow - 3107
Elven Arrow - 3137
Oridecon Arrow - 3147

Elemental Test:
Crystal Arrow vs. Dummy (21080) - 3162

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #8380 

* **Server Mode**: Renewal

**Description of Pull Request**: 

- When using Cart Cannon or Arm Cannon, the arrow attack you get from cannon balls is no longer affected by P.ATK
- Cart Cannon and Arm Cannon are no longer reduced by Res
- More consistent naming (PATK -> P.ATK, SMATK -> S.MATK)
- Fixes #8380

**Hints for Reviewers**:

- It seems that Cannon Balls are generally not adding any equip attack, but the damage of Cart Cannon and Arm Cannon is still increased by arrow attack, so my assumption is that this bonus is hard-coded into the two skills
- So far all tests indicate that all skills that use the simple defense formula also ignore Res, should be turned into a general rule later on after all skills have been tested
- Test numbers for Cart Cannon / Arm Cannon in the linked issue all match already, but if you run other tests you still might find small deviations when doing elemental tests, see #8414

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -3903,6 +3905,16 @@ static void battle_calc_attack_masteries(struct Damage* wd, struct block_list *s
 #endif
 				}
 				break;
+#ifdef RENEWAL
```
Comment (aleos89) [inline src/map/battle.cpp:3908]:
```suggestion
```
This skill is renewal only, so I think this is extra.

File: src/map/battle.cpp [hunk 2]
```diff
@@ -3903,6 +3905,16 @@ static void battle_calc_attack_masteries(struct Damage* wd, struct block_list *s
...
+			case GN_CARTCANNON:
+				// These skills add arrow attack as mastery attack instead of equip attack
+				// The only way to determine this is by confirming that the arrow attack isn't influenced by P.ATK
+				if (sd) {
+					struct status_data* tstatus = status_get_status_data(target);
+					ATK_ADD(wd->masteryAtk, wd->masteryAtk2, battle_attr_fix(src, target, sd->bonus.arrow_atk, sd->bonus.arrow_ele, tstatus->def_ele, tstatus->ele_lv));
+				}
+				break;
+#endif
```
Comment (aleos89) [inline src/map/battle.cpp:3917]:
```suggestion
```

**Review by aleos89 — APPROVED** [review]

File: src/map/battle.cpp [hunk 3]
```diff
@@ -3903,6 +3905,16 @@ static void battle_calc_attack_masteries(struct Damage* wd, struct block_list *s
 #endif
 				}
 				break;
+#ifdef RENEWAL
+			case GN_CARTCANNON:
+				// These skills add arrow attack as mastery attack instead of equip attack
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3910]:
```suggestion
				// This skill adds arrow attack as mastery attack instead of equip attack
```

File: src/map/battle.cpp [hunk 4]
```diff
@@ -3903,6 +3905,16 @@ static void battle_calc_attack_masteries(struct Damage* wd, struct block_list *s
...
+				// The only way to determine this is by confirming that the arrow attack isn't influenced by P.ATK
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3911]: Is this a documentation of how you found out that it should be changed like this or a TODO for the future?

File: src/map/battle.cpp [hunk 5]
```diff
@@ -3903,6 +3905,16 @@ static void battle_calc_attack_masteries(struct Damage* wd, struct block_list *s
...
+				if (sd) {
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3912]:
```suggestion
				if (sd != nullptr) {
```

File: src/map/battle.cpp [hunk 6]
```diff
@@ -3420,7 +3420,9 @@ static int battle_calc_equip_attack(struct block_list *src, int skill_id)
 		struct status_data *status = status_get_status_data(src);
 		map_session_data *sd = BL_CAST(BL_PC, src);
 
-		if (sd) // add arrow atk if using an applicable skill
+		// Cart Cannon is an arrow skill but adds arrow attack as mastery damage instead
+		if (sd && skill_id != GN_CARTCANNON)
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3424]:
```suggestion
		if (sd != nullptr && skill_id != GN_CARTCANNON)
```

File: src/map/battle.cpp [hunk 7]
```diff
@@ -3420,7 +3420,9 @@ static int battle_calc_equip_attack(struct block_list *src, int skill_id)
 		struct status_data *status = status_get_status_data(src);
 		map_session_data *sd = BL_CAST(BL_PC, src);
 
-		if (sd) // add arrow atk if using an applicable skill
+		// Cart Cannon is an arrow skill but adds arrow attack as mastery damage instead
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3423]:
```suggestion
		// Add arrow atk if using an applicable skill
		// Cart Cannon is an exceptional arrow skill and adds arrow attack as mastery damage instead
```

File: src/map/battle.cpp [hunk 8]
```diff
@@ -3420,7 +3420,9 @@ static int battle_calc_equip_attack(struct block_list *src, int skill_id)
...
+		if (sd && skill_id != GN_CARTCANNON)
+			// add arrow atk if using an applicable skill
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3425]:
```suggestion
```

**Review by Lemongrass3110 — APPROVED** [review]

File: src/map/battle.cpp (hunk 3 above)
Comment (Playtester) [reply src/map/battle.cpp:3910]: I put it in plural so people add similar skills to this list rather than creating their own checks.

File: src/map/battle.cpp (hunk 4 above)
Comment (Playtester) [reply src/map/battle.cpp:3911]: Both - so whenever someone wonders whether to add a skill to the list here or not they know how they can verify that.

File: src/map/battle.cpp (hunk 7 above)
Comment (Lemongrass3110) [reply src/map/battle.cpp:3423]: But you merged your check to the outer and not the inner (short) if.

File: src/map/battle.cpp (hunk 4 above)
Comment (Playtester) [reply src/map/battle.cpp]: Rephrased so it reflects reality better.

File: src/map/battle.cpp (hunk 7 above)
Comment (Playtester) [reply src/map/battle.cpp]: Reworked this part

File: src/map/battle.cpp [hunk 9]
```diff
@@ -3903,6 +3908,16 @@ static void battle_calc_attack_masteries(struct Damage* wd, struct block_list *s
...
+#ifdef RENEWAL
+			case GN_CARTCANNON:
+			case NC_ARMSCANNON:
+				// Arrow attack of these skills is not influenced by P.ATK so we add it as mastery attack
+				if (sd != nullptr) {
+					struct status_data* tstatus = status_get_status_data(target);
+					ATK_ADD(wd->masteryAtk, wd->masteryAtk2, battle_attr_fix(src, target, sd->bonus.arrow_atk, sd->bonus.arrow_ele, tstatus->def_ele, tstatus->ele_lv));
+				}
+				break;
+#endif
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3920]: Since you made it generic for all cannonballs in battle_calc_equip_attack, shouldnt we make it generic here too?

**Review by Lemongrass3110 — APPROVED** [review]

File: src/map/battle.cpp (hunk 9 above)
Comment (Playtester) [reply src/map/battle.cpp:3920]: As discussed on Discord, my assumption is that this part is in the skill-specific code on official servers, so I designed it on our side alike to be prepared for future skills.
