### PR TITLE
Restore Pre-Renewal Cast Sensor Behavior

### LINKED ISSUE #9252: Cast Sensor should only happen when there is a cast time
### rAthena Hash

499d852

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

When casting a skill on a monster with cast sensor, it will start attacking you, even if the skill has no cast time (including having 150+ DEX in pre-re).

When casting a skill on a monster that has a skill defined for the cast sensor event, it will use that skill, even if the skill has no cast time (including having 150+ DEX in pre-re).

### Expected Result

When casting a skill on a monster with cast sensor, it will only start attacking you, if the skill has a cast time.

When casting a skill on a monster that has a skill defined for the cast sensor event, it will only use that skill, if the skill has a cast time.

When having 150+ DEX in pre-re, then neither will ever trigger.

Issue was introduced in 60b0ed9.

### How to Reproduce

Use Cure on Golem.
Use Decrease Agi on Golem.
Use Kyrie Eleison on Golem.

Use Cure on Greatest General.
Use Decrease Agi on Greatest General.
Use Kyrie Eleison on Greatest General.

### Official Information

Tested:

Use Cure on Golem. -> No aggro
Use Decrease Agi on Golem. -> Aggro at 0-149 DEX, No aggro at 150+ DEX
Use Kyrie Eleison on Golem. -> Aggro at 0-149 DEX, No aggro at 150+ DEX

Use Cure on Greatest General. -> Counterspell
Use Decrease Agi on Greatest General. -> Counterspell at 0-149 DEX, No counterspell at 150+ DEX
Use Kyrie Eleison on Greatest General. -> Counterspell at 0-149 DEX, No counterspell at 150+ DEX

**Important: This bug only applies to pre-renewal. In renewal, no cast time is required!!!**

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9252 

* **Server Mode**: Pre-Renewal

**Description of Pull Request**: 

- In pre-re, cast sensor now only triggers again when the skill has a cast time
  * This got broken in 60b0ed9 but was a valid change for renewal
- Fixes #9252

### CODE REVIEW

File: src/map/unit.cpp [hunk 1]
```diff
@@ -2452,7 +2452,11 @@ int32 unit_skilluse_id2(struct block_list *src, int32 target_id, uint16 skill_id
 	// In official this is triggered even if no cast time.
 	clif_skillcasting(src, src->id, target_id, 0,0, skill_id, skill_lv, skill_get_ele(skill_id, skill_lv), casttime);
 
-	if (sd && target->type == BL_MOB) {
+	if (sd && target->type == BL_MOB
+#ifndef RENEWAL
+		&& (casttime > 0 || combo)
+#endif
+	) {
```
Comment (Daegaladh) [inline src/map/unit.cpp:2459]:
```suggestion
	if (sd != nullptr && target->type == BL_MOB
#ifndef RENEWAL
		&& (casttime > 0 || combo > 0)
#endif
	) {
```
