### PR TITLE
Fixes monster escape AI issues

### LINKED ISSUE #7904: Marine Sphere movement is not working properly
### rAthena Hash

eadfa053f6db830e0e769b7241aab5b8df651c92

### Client Date

2015-11-04

### Server Mode

Pre-Renewal

### Result

Tested in latest hash without modifications.

project_resurrection_Jx3rfHGcpA

As you can see in the video everytime you hit a Marine Sphere it starts moving but it randomly stops after moving between 0 and 7 cells.
It happens in any direction and with any type of attack.

### Relevant Log Output

_No response_

### Expected Result

1. Hit Marine Sphere any number of times
2. Marine Spheres moves 7 cells away from attacker

### How to Reproduce

1. Hit Marine Sphere any number of times
2. Marine Spheres moves between 0 and 7 cells away from attacker and stops

### Official Information

.

### Modifications that may affect results

_No response_

### LINKED ISSUE #7916: Mob ai seems broken
### rAthena Hash

0f1886927675a73e34636af4ed33caf7a13361ce

### Client Date

2015-11-04

### Server Mode

Pre-Renewal

### Just a few examples of mob ai being broken

Marine Sphere's movement being unpredictable
project_resurrection_Jx3rfHGcpA

`NPC_RUN` and `NPC_RANDOMNMOVE` don't work properly. Mobs can bypass them and start attacking.

Wink of Charm is broken too 
project_resurrection_BcY3ighaRZ

All of this has been tested again with latest rAthena, no modifications (other than setting packet version and credentials). For people that need the doublecheck, yes `monster_ai` was set to 0.

### Related PRs and Issues
https://github.com/rathena/rathena/issues/7904
https://github.com/rathena/rathena/pull/7905
https://github.com/rathena/rathena/pull/5236
https://github.com/rathena/rathena/pull/7333
https://github.com/rathena/rathena/issues/6371
https://github.com/rathena/rathena/pull/7264

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #7904 and fixes #7916

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Resolves NPC_RUN and NPC_RANDOMMOVE monsters not always reaching their intended escape distance.
  * Resolves Marine Sphere calling the run skill too early resulting in the distance escaped not always being the same.
  * Resolves Wink of Charm not forcing the target to fail skill use on the caster.
  * Renames the monster alchemist state to can_escape to fit multiple uses.
Thanks to @Leemonn!

### CODE REVIEW

File: src/map/mob.cpp [hunk 1]
```diff
@@ -2417,8 +2417,7 @@ void mob_log_damage(struct mob_data *md, struct block_list *src, int damage)
 void mob_damage(struct mob_data *md, struct block_list *src, int damage)
 {
 	if( src != nullptr && md->special_state.ai == AI_SPHERE && !md->dmglog[0].id ) {//LOne WOlf explained that ANYONE can trigger the marine countdown skill. [Skotlex]
-		md->state.alchemist = 1;
-		mobskill_use(md, gettick(), MSC_ALCHEMIST);
```
Comment (Lemongrass3110) [inline src/map/mob.cpp:2421]: If we remove this call, then MSC_ALCHEMIST is never used at all.

File: src/map/unit.cpp [hunk 2]
```diff
@@ -481,6 +481,14 @@ static TIMER_FUNC(unit_walktoxy_timer)
 		}
 #endif
 
+		// Remove any possible escape states present for mobs once they stopped moving.
+		if (bl->type == BL_MOB) {
+			mob_data *md = BL_CAST(BL_MOB, bl);
```
Comment (Lemongrass3110) [inline src/map/unit.cpp:486]: No need to BL_CAST anymore, since you already checked the type in the line above.

File: src/map/mob.cpp (hunk 1 above)
Comment (aleos89) [reply src/map/mob.cpp:2421]: It's a slight trick. It is used in the switch case where because it checks `ms[i]->cond` since NPC_RUN uses alchemist as the condition for Marine Sphere. We want to call NPC_RUN only when the value of can_escape is 1. Before we were making the MSC_ALCHEMIST call before the mob's state was changed/saved resulting in the flag=1 and the skill firing off too early.

File: src/map/unit.cpp (hunk 2 above)
Comment (aleos89) [reply src/map/unit.cpp:486]: If I read up a little more in the function I would have seen `md` is already defined too. 🙃

**Review by Lemongrass3110 — APPROVED** [review]
