### PR TITLE
Steal Coin Fixes and Integration

### LINKED ISSUE #2889: GS_DISARM, RG_STEALCOIN formula
* **Description of Issue**: 
  * Result: presently, even the src acknowledges that many skills such as GS_DISARM is using an unofficial formula!

  * Official Information:
extracted from 10.2, 14.1, and 15.2 zone, it's the same across all.
GS_DISARM strip chance
```
    baseRate= casterDEX / (4 * (7 - skLevel)) + casterLUK / (4 * (6 - skLevel));
    rate = baseRate + casterLevel - (tarAGI*baseRate/100)- tarLUK - tarLevel;
    if (GetServerRandom(0, 20000)%100 < rate)
        (strip weapon for 30 seconds or do -25% atk on mobs) 
```
(rate being per 100)

RG_STEALCOIN steal chance
```rate = (casterDEX/2 + 2 * (casterLevel - tarLevel) + (10*skill_lv) + casterLUK / 2);```
(rate is per 1000)
RG_STEALCOIN zeny amount
```amount = GetServerRandom(8*tarLevel, 10*tarLevel)```

if there are any more custom values like this that you need pulled from the zone, i can try to look into them. thank you. :)

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #2889 

* **Server Mode**: Both

**Description of Pull Request**: 

- Removed pc_steal_coin and moved functionality into the skill-specific code
- Steal Coin will now steal an extra [(skill_lv * target_lv) / 10] amount of Zeny
- Steal Coin can now hit every non-boss monster that has not been mugged yet
- Aftercast delay and SP cost are now only applied when the target is valid
- Added missing aftercast delay of 500ms in pre-renewal (already correct in renewal)
- Status changes no longer block Steal Coin from working
- Steal Coin now counts as 0 damage skill (breaking status changes, exp tap, draw aggro)
- Fixed client-sided display of how many coins were stolen
- Made code easier to read
- Follow-up to 1f48389
- Fixes #2889

### CODE REVIEW

File: src/map/skills/thief/mug.cpp [hunk 1]
```diff
@@ -14,13 +14,28 @@ void SkillMug::castendNoDamageId(block_list *src, block_list *target, uint16 ski
...
-	if(sd) {
-		if(pc_steal_coin(sd,target))
+	if (sd != nullptr && dstmd != nullptr) {
+		int32 target_lv = status_get_lv(target);
+		int32 rate = (10 * pc_checkskill(sd, RG_STEALCOIN));
+		rate += (sd->battle_status.dex / 2);
+		rate += (sd->battle_status.luk / 2);
+		rate += (2 * (sd->status.base_level - target_lv));
+
+		if (rnd_chance_official(rate, 1000))
```
Comment (Atemo) [inline src/map/skills/thief/mug.cpp]: Please include
```
#include <common/random.hpp>
```
and 
```
#include "map/battle.hpp"
```

File: src/map/skills/thief/mug.cpp [hunk 2]
```diff
@@ -14,13 +14,28 @@ void SkillMug::castendNoDamageId(block_list *src, block_list *target, uint16 ski
 	map_session_data* sd = BL_CAST( BL_PC, src );
 	mob_data *dstmd = BL_CAST(BL_MOB, target);
 
-	if(sd) {
-		if(pc_steal_coin(sd,target))
+	if (sd != nullptr && dstmd != nullptr) {
```
Comment (Lemongrass3110) [inline src/map/skills/thief/mug.cpp]: would be nice to return early here instead

File: src/map/skills/thief/mug.cpp [hunk 3]
```diff
@@ -14,13 +14,28 @@ void SkillMug::castendNoDamageId(block_list *src, block_list *target, uint16 ski
...
+		int32 target_lv = status_get_lv(target);
+		int32 rate = (10 * pc_checkskill(sd, RG_STEALCOIN));
```
Comment (Lemongrass3110) [inline src/map/skills/thief/mug.cpp]:
```suggestion
		int32 rate = 10 * pc_checkskill(sd, RG_STEALCOIN);
```

File: src/map/skills/thief/mug.cpp [hunk 4]
```diff
@@ -14,13 +14,28 @@ void SkillMug::castendNoDamageId(block_list *src, block_list *target, uint16 ski
...
+		rate += (sd->battle_status.dex / 2);
+		rate += (sd->battle_status.luk / 2);
+		rate += (2 * (sd->status.base_level - target_lv));
```
Comment (Lemongrass3110) [inline src/map/skills/thief/mug.cpp]:
```suggestion
		rate += sd->battle_status.dex / 2;
		rate += sd->battle_status.luk / 2;
		rate += 2 * (sd->status.base_level - target_lv);
```

File: src/map/skills/thief/mug.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/skills/thief/mug.cpp]: What is the benefit of this? Is this for faster compiling?

File: src/map/skills/thief/mug.cpp [hunk 5]
```diff
@@ -3,9 +3,12 @@
 
 #include "mug.hpp"
 
+#include <common/random.hpp>
+
 #include "map/clif.hpp"
 #include "map/mob.hpp"
 #include "map/pc.hpp"
+#include "map/battle.hpp"
```
Comment (Lemongrass3110) [inline src/map/skills/thief/mug.cpp]:
```suggestion
#include "map/battle.hpp"
#include "map/clif.hpp"
#include "map/mob.hpp"
#include "map/pc.hpp"
```

File: src/map/skills/thief/mug.cpp [hunk 6]
```diff
@@ -14,15 +17,31 @@ void SkillMug::castendNoDamageId(block_list *src, block_list *target, uint16 ski
...
+		battle_damage(src, target, 0, 1, skill_lv, 0, ATK_DEF, BF_WEAPON|BF_LONG|BF_NORMAL, true, tick, false);
 
-		}
-		else
-			clif_skill_fail( *sd, getSkillId() );
+		// Client uses skill_lv to show how many Zeny were stolen
+		clif_skill_nodamage(src, *target, getSkillId(), amount);
 	}
+	else
+		clif_skill_fail(*sd, getSkillId());
```
Comment (Lemongrass3110) [inline src/map/skills/thief/mug.cpp]:
```suggestion
	if (!rnd_chance_official(rate, 1000))
	{
		clif_skill_fail(*sd, getSkillId());
		return;
	}

	dstmd->state.steal_coin_flag = 1;

	// Zeny Steal Amount
	int32 amount = rnd_value(8 * target_lv, 10 * target_lv);
	amount += (skill_lv * target_lv) / 10;

	pc_getzeny(sd, amount, LOG_TYPE_STEAL);

	// This triggers a 0 damage event and might make the monster switch target to caster
	battle_damage(src, target, 0, 1, skill_lv, 0, ATK_DEF, BF_WEAPON|BF_LONG|BF_NORMAL, true, tick, false);

	// Client uses skill_lv to show how many Zeny were stolen
	clif_skill_nodamage(src, *target, getSkillId(), amount);
```

**Review by Lemongrass3110 — APPROVED** [review]
