### PR TITLE
Renewal Spiral Pierce, Element vs. Status Attack

### LINKED ISSUE #8410: Renewal Spiral Pierce Formula
### rAthena Hash

17a6d03

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Spiral Pierce multiplies weight with 0.7 and adds it to EquipATK
Secondary size modifiers are 115% on small and 85% on large.
Weight is affected by element.
Mastery attack does not affect damage.

### Relevant Log Output

_No response_

### Expected Result

Spiral Pierce takes base damage (StatusATK + WeaponATK + EquipATK), adds Weight to it, then multiplies it with 0.7.
Secondary size modifiers are 130% on small and 115% on medium.
Weight is not affected by element.
Mastery attack affects damage.

Formula: [floor(floor((ATK + Weight) x 0.7) x SizeModifier) + masteryATK) x SkillRatio x (BaseLvl ÷ 100)]

### How to Reproduce

Use Spiral Pierce, check damage.
Can in theory use Hocus Pocus to get Power Maximize to remove randomness.

### Official Information

Lord Knight 99/70, Hunting Spear, Clashing Spiral 1, Spear Mastery 5

All Dummies except Ghost - 996x5 - 1070x5 <-- rAthena 950-1058x5
Ghost Dummy - 964x5 - 1040x5

Brionac
vs. Neutral 21065 - 814-900x5 <-- rAthena 796-910x5
vs. Poison 21082 - 766-834x5
vs. Holy 21083 - 612x5
vs. Dark 21084 - 864-978x5
vs. Ghost 21085 - 800-892x5
vs. Undead 21086 - 864-978x5

Normal vs Neutral Dummy:
Hunting Spear - 176-230
Brionac - 185-240

Spear Mastery 9 + Level 100/1
Hunting Spear vs. Neutral - 954-1040x5
Brionac vs. Neutral - 770-860x5

Spear Master 5 + Level 100/1
Hunting Spear vs. Neutral - 928-1006x5
Brionac vs. Neutral - 738-830x5

Rune Knight - BaseLevel 175/70, Power Maximize
grafik
grafik

vs. Large Dummy
grafik
grafik

vs. Medium Dummy
grafik
grafik

vs. Small Dummy
grafik
grafik

vs. Ghost Dummy (older elemental table with 70%)
grafik
grafik

Additional info:

status atk = 53

Ghost dummy - no endow/MW
162 damage in-game
ceil(53*0.7)*2 = 76

Earth dummy - Fire MW
375 damage in-game
ceil(53*1.5)*2 = 160

Fire dummy - Fire MW
40 damage in-game
ceil(53*0.25)*2 = 28

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #8410 

* **Server Mode**: Renewal

**Description of Pull Request**: 

- When using Spiral Pierce the base damage will now be multiplied with 0.7
- Weight bonus of Spiral Pierce is no longer affected by elemental adjustments
- Size modifiers updated: Small 130%, Medium 115%, Large 100%
- Spiral Pierce will now store its base damage in equipAtk to prevent rounding errors (temporary solution)
- Status Attack will now first apply the elemental table before doubling the right-hand damage
- Fixes #8410

**Hints for Reviewers**:

Further tests in #8380 indicate that the attribute table should be applied to the sum of weaponAtk and equipAtk. And the tests on Spiral Pierce show that later adjustments (such as the 0.7x damage multiplier and the 1.15x / 1.3x size modifiers) apply to the sum of statusAtk, weaponAtk and equipAtk. As long as we keep those values in separate variables, we will always have rounding issues with our damage.
The solution for Spiral Pierce to put everything into equipAtk is just a temporary solution, we should consider putting the different attack values into a single variable, but first we need to go through all the status changes and other abilities that only affect one of them in a percentual way. This should be done gradually so we don't have one huge PR that changes thousands of lines of code. Maybe first combine equipAtk and weaponAtk into just equipAtk and at the end merge it with statusAtk.
We should also check how percentAtk behaves in the future. I assume it was put into a separate variable because the AtkRate bonus should not affect other bonuses.

On the status attack change, see also #8380 for further proof that this applies globally to all skills and normal attacks.

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -4047,26 +4042,33 @@ static void battle_calc_skill_base_damage(struct Damage* wd, struct block_list *
...
-				battle_calc_damage_parts(wd, src, target, skill_id, skill_lv);
-				wd->masteryAtk = 0; // weapon mastery is ignored for spiral
+				// Official 70% damage modifier is applied to base attack + weight
+				ATK_RATE(wd->equipAtk, wd->equipAtk2, 70);
 				
-				switch (tstatus->size) { //Size-fix. Is this modified by weapon perfection?
-					case SZ_SMALL: //Small: 115%
-						ATK_RATE(wd->damage, wd->damage2, 115);
-						RE_ALLATK_RATE(wd, 115);
+				switch (tstatus->size) { //Second size fix
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:4064]:
```suggestion
				// Second size fix
				switch (tstatus->size) {
```
Why do we call it "second"?

File: src/map/battle.cpp [hunk 2]
```diff
@@ -4047,26 +4042,33 @@ static void battle_calc_skill_base_damage(struct Damage* wd, struct block_list *
...
+				short index = sd->equip_index[EQI_HAND_R];
 				if (index >= 0 &&
 					sd->inventory_data[index] &&
 					sd->inventory_data[index]->type == IT_WEAPON)
-					wd->equipAtk += sd->inventory_data[index]->weight*7/100; // weight from spear is treated as equipment ATK on official [helvetica]
+					wd->equipAtk += sd->inventory_data[index]->weight / 10;
 
-				battle_calc_damage_parts(wd, src, target, skill_id, skill_lv);
-				wd->masteryAtk = 0; // weapon mastery is ignored for spiral
+				// Official 70% damage modifier is applied to base attack + weight
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:4061]:
```suggestion
				// 70% damage modifier is applied to base attack + weight
```

File: src/map/battle.cpp [hunk 3]
```diff
@@ -3969,6 +3962,8 @@ static void battle_calc_damage_parts(struct Damage* wd, struct block_list *src,s
 		wd->statusAtk = battle_attr_fix(src, target, wd->statusAtk, ELE_NEUTRAL, tstatus->def_ele, tstatus->ele_lv);
 		wd->statusAtk2 = battle_attr_fix(src, target, wd->statusAtk2, ELE_NEUTRAL, tstatus->def_ele, tstatus->ele_lv);
 	}
+	// Right-hand status attack is doubled after elemental adjustments
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3965]:
```suggestion

	// Right-hand status attack is doubled after elemental adjustments
```

File: src/map/battle.cpp [hunk 4]
```diff
@@ -3401,10 +3392,12 @@ static bool battle_skill_stacks_masteries_vvs(uint16 skill_id, e_bonus_chk_flag
 		case LG_EARTHDRIVE:
 		case NPC_DRAGONBREATH:
 			return false;
+#ifndef RENEWAL
 		case LK_SPIRALPIERCE:
 			// Spiral Pierce is influenced only by refine bonus and Star Crumbs for players
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3397]:
```suggestion
			// In Pre-Renewal Spiral Pierce is influenced only by refine bonus and Star Crumbs for players
```

File: src/map/battle.cpp [hunk 5]
```diff
@@ -4047,26 +4042,33 @@ static void battle_calc_skill_base_damage(struct Damage* wd, struct block_list *
...
-				wd->masteryAtk = 0; // weapon mastery is ignored for spiral
+				// Official 70% damage modifier is applied to base attack + weight
+				ATK_RATE(wd->equipAtk, wd->equipAtk2, 70);
 				
-				switch (tstatus->size) { //Size-fix. Is this modified by weapon perfection?
-					case SZ_SMALL: //Small: 115%
-						ATK_RATE(wd->damage, wd->damage2, 115);
-						RE_ALLATK_RATE(wd, 115);
+				switch (tstatus->size) { //Second size fix
+					case SZ_SMALL: //Small: 130%
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:4065]:
```suggestion
					case SZ_SMALL:
```

File: src/map/battle.cpp [hunk 6]
```diff
@@ -4047,26 +4042,33 @@ static void battle_calc_skill_base_damage(struct Damage* wd, struct block_list *
...
+						ATK_RATE(wd->equipAtk, wd->equipAtk2, 130);
 						break;
-					//case SZ_MEDIUM: //Medium: 100%
-					case SZ_BIG: //Large: 85%
-						ATK_RATE(wd->damage, wd->damage2, 85);
-						RE_ALLATK_RATE(wd, 85);
+					case SZ_MEDIUM: //Medium: 115%
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:4068]:
```suggestion
					case SZ_MEDIUM:
```

File: src/map/battle.cpp [hunk 7]
```diff
@@ -4047,26 +4042,33 @@ static void battle_calc_skill_base_damage(struct Damage* wd, struct block_list *
...
+						ATK_RATE(wd->equipAtk, wd->equipAtk2, 115);
 						break;
+					//case SZ_BIG: //Large: 100%
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:4071]:
```suggestion
					case SZ_BIG:
						ATK_RATE(wd->equipAtk, wd->equipAtk2, 100);
						break;
```
Compiler will optimize it away.

**Review by Lemongrass3110 — APPROVED** [review]
I would prefer to have the element changes split from the spiral pierce changes, as it affects all skills.

File: src/map/battle.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/battle.cpp:4065]: To make it clear that it does not replace the original size fix on the weaponAtk and that this is intentional.

File: src/map/battle.cpp (hunk 5 above)
Comment (Playtester) [reply src/map/battle.cpp:4066]: Why remove the additional info here? Feel people might think the numbers were a mistake (since they were different until episode 18).

File: src/map/battle.cpp (hunk 7 above)
Comment (Playtester) [reply src/map/battle.cpp:4072]: Even if it does, I rather leave it away completely then. I like my version more with a comment telling you what the value is.

File: src/map/battle.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/battle.cpp]: Improved the comment as discussed
