### PR TITLE
Adjusts Comet to a unit skill type

### LINKED ISSUE #5951: Comet/Earth Strain and Maya Card
* **rAthena Hash**: c44fdaf

* **Client Date**:  20200401

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 1 - Maya Card is reflecting the damage of the Comet. 
                2 - Maya Card is not reflecting the damage of the Earth Strain used by Release. 
  
* Expected Result: 1 - Maya Card does not work on Comet. Comet is a ground skill (13x13 cells), Maya only reflect single target magic skill. 
  2 - Release is a single target magic skill, so should be reflected by Maya Card. 
  
* How to Reproduce: Use Comet/Release (Earth Strain) in another player that has a shield with Maya Card. 
  * Official Information: https://divine-pride.net/database/item/4146/maya-card

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #5951

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Adjusts the behavior of Comet to a unit skill type.
  * Comet will now behave properly around Maya Card and other unit skill type interactions.
Thanks to @Felleonel and @Playtester!

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -14207,6 +14200,10 @@ int skill_unit_onplace_timer(struct skill_unit *unit, struct block_list *bl, t_t
 					if (rnd()%100 < unit->val1)
 						skill_attack(BF_WEAPON,ss,&unit->bl,bl,sg->skill_id,sg->skill_lv,tick,0);
 					break;
+				case WL_COMET:
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:14203]: Maybe check if NPC_COMET should be added here as well.
Maybe @Atemo or @mrjnumber1 know.

**Review by Lemongrass3110 — APPROVED** [review]

**Review by Lemongrass3110 — APPROVED** [review]
