### PR TITLE
NPC_INVINCIBLE and Spell Breaker

### LINKED ISSUE #8228: SC_INVINCIBLE - ATK, ASPD, Speed bonus
### rAthena Hash

c546e67

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

Current the skill increases damage by 75% and movement speed by 75%.

### Relevant Log Output

_No response_

### Expected Result

Officially the skill increases ATKpercent by 100.
The movement speed is increased by 50 (same as NPC_AGIUP).
It also gives 700 extra ASPD (works like TWOHANDQUICKEN except it's 700 instead of 300).

### How to Reproduce

Give a monster only this skill, wait until it activates, check ATK, movement speed and ASPD increase.
Or just verify via source code.

### Official Information

Information was provided by mrj confirmed by Tharis.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #8228 

* **Server Mode**: Both

**Description of Pull Request**: 

- NPC_INVINCIBLE now grants SC_INVINCIBLE for 300s instead of unlimited
- NPC_INVINCIBLEOFF and MER_INVINCIBLEOFF2 now just end SC_INVINCIBLE instead of having their own status change
- SC_INVINCIBLE now works like plant mode instead of just setting incoming damage to 1
- SC_INVINCIBLE now increases ATKpercent by 100 instead of increasing all damage by 75%
- SC_INVINCIBLE no longer blocks skills
- SC_INVINCIBLE now increases movement speed by 50% instead of 75%
- SC_INVINCIBLE now increases ASPD strongly
- Quagmire can no longer prevent ASPD increase (it still ends various status changes and prevents them)
- If you counter Spell Breaker with Magic Rod you now receive 20% of the caster's MaxSP
- Spell Breaker will now only deal HP damage on level 5
- Spell Breaker now can deal damage to bosses to 10% in pre-re (cannot be reduced by SC_INVINCIBLE unless you enable the "invincible_nodamage" setting)
- Spell Breaker will no longer deal damage if it would be lethal
- Added missing animation of Spell Breaker's damage
- Fixes #8228

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -9767,43 +9765,45 @@ int skill_castend_nodamage_id (struct block_list *src, struct block_list *bl, ui
...
+				sp = status_percent_damage(bl, src, 0, -20, false);
+				status_heal(bl, 0, sp, 2);
+			}
+			else {
+				struct unit_data* ud = unit_bl2ud(bl);
+				int bl_skill_id = 0, bl_skill_lv = 0, hp = 0;
 				if (!ud || ud->skilltimer == INVALID_TIMER)
 					break; //Nothing to cancel.
 				bl_skill_id = ud->skill_id;
 				bl_skill_lv = ud->skill_lv;
```
Comment (aleos89) [inline src/map/skill.cpp:9779]: GitHub won't let me make a suggestion to remove these two lines.

File: src/map/skill.cpp [hunk 2]
```diff
@@ -9767,43 +9765,45 @@ int skill_castend_nodamage_id (struct block_list *src, struct block_list *bl, ui
...
-				if (status_has_mode(tstatus,MD_STATUSIMMUNE)) { //Only 10% success chance against status immune. [Skotlex]
-					if (rnd()%100 < 90)
+				if (status_has_mode(tstatus, MD_STATUSIMMUNE)) { //Only 10% success chance against status immune. [Skotlex]
+					if (rnd() % 100 < 90)
```
Comment (aleos89) [inline src/map/skill.cpp:9781]:
```suggestion
					if (rnd_value(0, 100) < 90)
```

Comment (aleos89) [inline src/map/skill.cpp:9781]:
```suggestion
					if (rnd_value(1, 100) < 90)
```

File: src/map/skill.cpp [hunk 3]
```diff
@@ -9767,43 +9765,45 @@ int skill_castend_nodamage_id (struct block_list *src, struct block_list *bl, ui
...
+				else // HP damage does not work on bosses in renewal
+#endif
+					if (skill_lv >= 5 && (!dstsd || map_flag_vs(bl->m))) //HP damage only on pvp-maps when against players.
+						hp = tstatus->max_hp / 50; //Siphon 2% HP at level 5
 
-				if(hp || sp)
-					status_heal(src, hp, sp, 2);
+				clif_skill_nodamage(src, bl, skill_id, skill_lv, 1);
+				unit_skillcastcancel(bl, 0);
+				sp = skill_get_sp(bl_skill_id, bl_skill_lv);
```
Comment (aleos89) [inline src/map/skill.cpp:9795]:
```suggestion
				sp = skill_get_sp(ud->skill_id, ud->skill_lv);
```

File: src/map/skill.cpp (hunk 1 above)
Comment (aleos89) [inline src/map/skill.cpp:9779]: GitHub won't let me suggest the removal of the two lines above. You could also define the `int hp = 0;` here after the break!

File: src/map/skill.cpp [hunk 4]
```diff
@@ -9767,43 +9765,45 @@ int skill_castend_nodamage_id (struct block_list *src, struct block_list *bl, ui
...
-				struct unit_data *ud = unit_bl2ud(bl);
-				int bl_skill_id=0,bl_skill_lv=0,hp = 0;
+			if (dstsd && tsc && tsc->getSCE(SC_MAGICROD)) {
+				// If target enemy player has Magic Rod, then 20% of your SP is transferred to that player
+				sp = status_percent_damage(bl, src, 0, -20, false);
+				status_heal(bl, 0, sp, 2);
+			}
+			else {
+				struct unit_data* ud = unit_bl2ud(bl);
+				int bl_skill_id = 0, bl_skill_lv = 0, hp = 0;
```
Comment (aleos89) [inline src/map/skill.cpp:9775]:
```suggestion
```

**Review by aleos89 — APPROVED** [review]
