### PR TITLE
Resolves a potential crash from Howling Mine

### LINKED ISSUE #8146: Howling Mine SC returns nullptr and crashes server
### rAthena Hash

b7da245d6

### Client Date

2023-11-10

### Server Mode

Renewal

### Result

Using Howling Mine (Rebellion) Grenade launcher skill on a bunch of monsters then using flicker will lead to a server crash due to it being returned as nullptr
fgdfgdfgf

### Relevant Log Output

```Shell
Posted image above
```

### Expected Result

For it to not crash the server 

### How to Reproduce

Spam Howling mine & Flicker on monsters repeatedly

### Official Information

should..not crash the server?

### Modifications that may affect results

None

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #8146

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * Minor cleanups to ensure the Howling Mine status is active before accessing.
Thanks to @LadyNanuia!

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -6892,14 +6892,16 @@ int skill_castend_damage_id (struct block_list* src, struct block_list *bl, uint
 				break;
 			}
 			// Triggered by RL_FLICKER
-			if (sd && sd->flicker && tsc && tsc->getSCE(SC_H_MINE) && tsc->getSCE(SC_H_MINE)->val2 == src->id) {
+			if (sd && sd->flicker) {
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:6895]: Seeing the check above: Shouldnt we remove this if?

File: src/map/skill.cpp [hunk 2]
```diff
@@ -6892,14 +6892,16 @@ int skill_castend_damage_id (struct block_list* src, struct block_list *bl, uint
...
 				// Splash damage around it!
 				map_foreachinrange(skill_area_sub, bl, skill_get_splash(skill_id, skill_lv), BL_CHAR|BL_SKILL,
 					src, skill_id, skill_lv, tick, flag|BCT_ENEMY|1, skill_castend_damage_id);
 				flag |= 1; // Don't consume requirement
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:6899]:
```suggestion
```
Should be removed (see below in line 6907).

**Review by Lemongrass3110 — APPROVED** [review]
