### PR TITLE
Provoke by Non-PC / Demon Bane

### LINKED ISSUE #9469: Provoke Powerskill
### rAthena Hash

494cc86

### Client Date

2021-11-03

### Server Mode

Pre-Renewal, Renewal

### Result

When a monster uses Level 10 Provoke, it increases ATK by 32% and reduces DEF by 55%.

### Expected Result

When a monster uses Level 10 Provoke, it increases ATK by 0% and reduces DEF by 100%.

It still fails when your base level is higher than the monster level.

### How to Reproduce

Make a monster (e.g. Carat) cast Provoke on you and check damage.

### Official Information

High Priest 94/70, no equip, 43+7 STR and 99+7 VIT vs. Carat

No provoke - 106-109 damage dealt, ~176-286 damage taken.
Provoked - 106-109 damage dealt, ~298-382 damage taken.

Aloevera - 109-112 damage dealt

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9469 

* **Server Mode**: Both

**Description of Pull Request**: 

- When a non-PC uses level 10 Provoke, it now reduces DEF by 100% and does not increase damage
- Fixed small rounding issue with Demon Bane
- Fixes #9469

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -2279,7 +2279,7 @@ int64 battle_addmastery(map_session_data *sd,struct block_list *target,int64 dmg
 	if((skill = pc_checkskill(sd,AL_DEMONBANE)) > 0 &&
 		target->type == BL_MOB && //This bonus doesn't work against players.
 		(battle_check_undead(status->race,status->def_ele) || status->race == RC_DEMON) )
-		damage += (skill*(int32)(3+(sd->status.base_level+1)*0.05));	// submitted by orn
+		damage += static_cast<int64>(skill * (sd->status.base_level / 20.0 + 3.0));
```
Comment (Lemongrass3110) [inline src/map/battle.cpp]:
```suggestion
		damage += static_cast<decltype(damage)>(skill * (sd->status.base_level / 20.0 + 3.0));
```

**Review by Lemongrass3110 — APPROVED** [review]
