### PR TITLE
Correct Effects for Confusion and Signum Crucis

### LINKED ISSUE #9415: Confusion vs. Signum Crucis
### rAthena Hash

4c57c2a

### Client Date

2021-11-03

### Server Mode

Pre-Renewal, Renewal

### Result

Signum Crucis sends the OPT2 value 0x8.

Confusion does not send any OPT2 value. Instead it does the ET_QUESTION emotion.

### Expected Result

Signum Crucis does not send any OPT2 value. It just makes monster do ET_SWEAT the first time they are affected by it.

Confusion sends the OPT2 value 0x8. It does not make the target do the ET_QUESTION emotion.

### How to Reproduce

Use Signum Crucis / Pang Voice on a target.

OPT2 = 0x8 plays a specific "Confusion" sound. That way you can tell if it was sent.

### Official Information

Verified by testing on official servers.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9415 

* **Server Mode**: Both

**Description of Pull Request**: 

- Fixed the Confusion effect being misused by Signum Crucis
- Confusion no longer makes target show a "?" emotion on success, instead it plays the "Confusion" sound
- Signum Crucis no longer plays the "Confusion" sound, but monsters still "sweat" when affected by it
- Signum Crucis can now only succeed once per monster (it lasts unlimited)
- Fixes #9415

### CODE REVIEW

File: src/map/script_constants.hpp [hunk 1]
```diff
@@ -10735,7 +10735,7 @@
 	export_constant(OPT2_POISON);
 	export_constant(OPT2_CURSE);
 	export_constant(OPT2_SILENCE);
-	export_constant(OPT2_SIGNUMCRUCIS);
+	export_constant(OPT2_CONFUSION);
```
Comment (Lemongrass3110) [inline src/map/script_constants.hpp:10739]: Deprecate with date please.

File: src/map/status.hpp [hunk 2]
```diff
@@ -2971,7 +2971,7 @@ enum e_sc_opt2 : uint16 {
 	OPT2_POISON		= 0x0001,
 	OPT2_CURSE		= 0x0002,
 	OPT2_SILENCE		= 0x0004,
-	OPT2_SIGNUMCRUCIS	= 0x0008, //Confusion
+	OPT2_CONFUSION	= 0x0008,
```
Comment (HopeItBuilds) [inline src/map/status.hpp]:
```suggestion
	OPT2_CONFUSION		= 0x0008,
```

File: src/map/script_constants.hpp (hunk 1 above)
Comment (Playtester) [reply src/map/script_constants.hpp:10739]: Fixed.

File: src/map/script_constants.hpp [hunk 3]
```diff
@@ -10735,7 +10735,8 @@
 	export_constant(OPT2_POISON);
 	export_constant(OPT2_CURSE);
 	export_constant(OPT2_SILENCE);
-	export_constant(OPT2_SIGNUMCRUCIS);
+	export_deprecated_constant2("OPT2_SIGNUMCRUCIS", OPT2_CONFUSION); // June 2025
```
Comment (Atemo) [inline src/map/script_constants.hpp]:
```suggestion
	export_deprecated_constant3("OPT2_SIGNUMCRUCIS", OPT2_CONFUSION, "OPT2_CONFUSION"); // June 2025
```
It will also display "Please use 'OPT2_CONFUSION' instead!"

File: src/map/script_constants.hpp [hunk 4]
```diff
@@ -10735,7 +10735,8 @@
 	export_constant(OPT2_POISON);
 	export_constant(OPT2_CURSE);
 	export_constant(OPT2_SILENCE);
-	export_constant(OPT2_SIGNUMCRUCIS);
+	export_deprecated_constant3("OPT2_SIGNUMCRUCIS", OPT2_CONFUSION, "OPT2_CONFUSION"); // June 2025
```
Comment (Lemongrass3110) [inline src/map/script_constants.hpp:10738]:
```suggestion
	export_deprecated_constant2("OPT2_SIGNUMCRUCIS", OPT2_CONFUSION); // June 2025
```

**Review by Lemongrass3110 — APPROVED** [review]

File: src/map/script_constants.hpp (hunk 4 above)
Comment (Lemongrass3110) [reply src/map/script_constants.hpp:10738]: Just saw the comment from Atemo.
Ignore mine.
