### PR TITLE
Increases the server config character limit

### LINKED ISSUE #5324: Inter_Athena MYSQL Password Setting Characters Limited
* **rAthena Hash**: https://github.com/rathena/rathena/commit/78676d8a6f5280b858da6cda67b1b0ffeb6beb69

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: Cannot use password more than 31 characters in inter_athena.
  * Result: Password that read by emulator limited to 31 characters.
  * Expected Result: If its intended with this maximum limit, then let me know, ill close this issue.
  * How to Reproduce: Try to start emulator and you can see the remaining characters are not included in the error.

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #5324

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Adjusts the Login, Character and Map server's ID, password, schema, and codepage character limit from 31 to 1023.
  * Adjusts the Login, Character, and Map server's IP character limit from 63 to 1023.
Thanks to @reunite-ro!

### CODE REVIEW

File: src/map/map.cpp [hunk 1]
```diff
@@ -4268,18 +4268,18 @@ int log_sql_init(void)
 	// log db connection
 	logmysql_handle = Sql_Malloc();
 
-	ShowInfo("" CL_WHITE "[SQL]" CL_RESET ": Connecting to the Log Database " CL_WHITE "%s" CL_RESET " At " CL_WHITE "%s" CL_RESET "...\n",log_db_db,log_db_ip);
-	if ( SQL_ERROR == Sql_Connect(logmysql_handle, log_db_id, log_db_pw, log_db_ip, log_db_port, log_db_db) ){
+	ShowInfo("" CL_WHITE "[SQL]" CL_RESET ": Connecting to the Log Database " CL_WHITE "%s" CL_RESET " At " CL_WHITE "%s" CL_RESET "...\n",log_db_db,log_db_ip.c_str());
+	if ( SQL_ERROR == Sql_Connect(logmysql_handle, log_db_id.c_str(), log_db_pw.c_str(), log_db_ip.c_str(), log_db_port, log_db_db.c_str()) ){
 		ShowError("Couldn't connect with uname='%s',passwd='%s',host='%s',port='%d',database='%s'\n",
-			log_db_id, log_db_pw, log_db_ip, log_db_port, log_db_db);
+			log_db_id.c_str(), log_db_pw.c_str(), log_db_ip.c_str(), log_db_port, log_db_db.c_str());
```
Comment (Lemongrass3110) [inline src/map/map.cpp:4274]: shouldnt we remove echoing the password at all?

**Review by Lemongrass3110 — APPROVED** [review]
Basically I agree with these changes and they look good to me.
But it just got me thinking if we should put all of this duplicate code into a class.
Can be done later on anyway so that we can close the issue for the time being.

**Comment by aleos89** [comment]
Yeah I figured we could do a good refactor later.
