### PR TITLE
ATKpercent for monsters

### LINKED ISSUE #3538: NPC_POWERUP skill effect on monster physical damage
* **rAthena Hash**: 

* **Client Date**: x

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: NPC_POWERUP skill should triple monsters physical damage and hit but does not affect their skills damage and magic damage. Currently in rAthena the hit bonus works perfectly but not the physical damage bonus.
  * Expected Result:  This skill should increase the physical damage of monsters as well
  * How to Reproduce:  Spawn biolab monster (seyren or harword) and check the damage different before and after they use NPC_POWERUP skill.
  * Official Information:https://www.youtube.com/watch?v=UKFt58_sGPc&list=LL-iKjLO3OiG5Nrt_nfbSbig&index=3&t=0s

kRO Rune knight in ET

At 1.50 min : Before powerup skill, ifrit did damage around 4k+ to  5k+ normal physical damage while the fire breath damage was 14k+
At 3.25 min: After powerup skill, ifrit did damage around 12k+ to  15k+ normal physical damage while the fire breath damage was maintained 14k+
  

* **Modifications that may affect results**: 
  
  
under battle.cpp, section Check damage through status, look for:
//SC effects from caster side.
	sc = status_get_sc(src);
	if (sc && sc->count) {

and add this line
```if (src->type == BL_MOB ) {```
	```if (sc->data[SC_INCATKRATE] && !skill_id) {```
		```damage += damage * 2;```
		```}```
	```}```

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #3538 

* **Server Mode**: Both

**Description of Pull Request**: 

- Most NPC skills are now influenced by ATKpercent again
- LK_SPIRALPIERCE is now only not influenced by ATKpercent when used by players
- Introduced a new enum for bonus check flags
- Follow-up to 03f07ab
- Fixes #3538

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -3359,11 +3359,12 @@ static bool attack_ignores_def(struct Damage* wd, struct block_list *src, struct
...
  * This function lists which skills are unaffected by refine bonus, masteries, Star Crumbs and Spirit Spheres
  * This function is also used to determine if atkpercent applies
+ * @param src: Source of the attack
  * @param skill_id: Skill being used
- * @param type 1 - Checking refine bonus; 2 - Checking Star Crumb bonus
+ * @param chk_flag: The bonus that is currently being checked for, see e_bonus_chk_flag
  * @return true = bonus applies; false = bonus does not apply
  */
-static bool battle_skill_stacks_masteries_vvs(uint16 skill_id, int type)
+static bool battle_skill_stacks_masteries_vvs(struct block_list &src, uint16 skill_id, int chk_flag)
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:3367]:
```suggestion
static bool battle_skill_stacks_masteries_vvs(struct block_list &src, uint16 skill_id, e_bonus_chk_flag chk_flag)
```

**Review by Lemongrass3110 — APPROVED** [review]
