### PR TITLE
Gravitational Field on Emperium

### LINKED ISSUE #9149: Gravitational Field should deal 400 damage on Emperium
### rAthena Hash

0fed4cc

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

Gravitational Field deals 200 + 200 * level damage to Emperium.

### Expected Result

Gravitational Field deals 400 damage to Emperium on all levels.

### How to Reproduce

Need a GM to spawn an Emp for you in pre-re. Then cast Gravitational Field on it on various levels.

### Official Information

Official information available and also confirmed through test.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9149

* **Server Mode**: Pre-Renewal

**Description of Pull Request**: 

- Gravitational Field will now always deal 400 damage on Emperium on all levels in pre-re
- Renewal is unaffected
- Fixes #9149

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -9651,6 +9651,12 @@ struct Damage battle_calc_misc_attack(struct block_list *src,struct block_list *
 		case HW_GRAVITATION:
 			md.damage = 200 + 200 * skill_lv;
 			md.dmotion = 0; //No flinch animation
+			if (target->type == BL_MOB) {
+				mob_data* mob = reinterpret_cast<mob_data*>(target);
+				// Deals 400 damage to Emperium on all levels
+				if (mob != nullptr && mob->mob_id == MOBID_EMPERIUM)
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:9657]:
```suggestion
				if (mob.mob_id == MOBID_EMPERIUM)
```

**Review by Lemongrass3110 — APPROVED** [review]
