### PR TITLE
Endure Effect Quick Fix

### LINKED ISSUE #9064: bNoWalkDelay broken
### rAthena Hash

82b1764

### Client Date

2020-07-15

### Server Mode

Pre-Renewal

### Result

Starting from 82b1764, unlimited endure has stopped working for items using item bonus bNoWalkDelay.

For the meantime, replacing it with the old unlimited endure script `sc_start4 SC_ENDURE,60000,10,0,0,1;` will allow the item to reproduce the unlimited endure effects. (Haven't tried Eddga Card)

Endure, as a skill, works as intended when activated normally.

### Relevant Log Output

```Shell

```

### Expected Result

Using the script in an item will give characters unlimited endure effect (non gvg maps).

### How to Reproduce

Use `bonus bNoWalkDelay;` as an item script.
OR
Equip items that normally offer the same effect (2199 Ahura Mazda).

### Official Information

Will give an unlimited endure (no flinch) effect.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9064

* **Server Mode**: Both

**Description of Pull Request**: 

- Partially reverted 82b1764
- Any effect that grants "no damage motion" that is not SC_ENDURE is working again
- SC_ENDURE is correctly disabled on GVG2 and Battlegrounds again
- Fixes #9064

### CODE REVIEW

**Review by Atemo — APPROVED** [review]

File: src/map/clif.cpp [hunk 1]
```diff
@@ -5306,6 +5305,8 @@ int32 clif_damage(block_list& src, block_list& dst, t_tick tick, int32 sdelay, i
 	if(&src == &dst) 
 		unit_setdir(&src, unit_getdir(&src));
 
+	// In case this assignment is bypassed by DMG_MULTI_HIT_CRITICAL
+	type = clif_calc_delay( dst, type, div, damage+damage2, ddelay );
```
Comment (Lemongrass3110) [inline src/map/clif.cpp:5309]:
```suggestion
	if( type != DMG_MULTI_HIT_CRITICAL ){
		type = clif_calc_delay( dst, type, div, damage+damage2, ddelay );
	}

```

**Review by Lemongrass3110 — APPROVED** [review]
