### PR TITLE
Ensemble skills now apply fatigue

### LINKED ISSUE #7376: Ensemble Fatigue not working
### rAthena Hash

b568f2fb1

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

SC_ENSEMBLEFATIGUE is broken, it is not appearing even after you use an ensemble skill.

### Relevant Log Output

_No response_

### Expected Result

SC_ENSEMBLEFATIGUE should start after a bard and dancer or clown and gypsy uses an ensemble skill.

### How to Reproduce

run rAthena server, cast any ensemble skills, and wait for the ensemble to end and you will see.

### Official Information

This was already implemented in #5014 and I know it was working back then, but now it doesn't.

### Modifications that may affect results

none

### LINKED ISSUE #9414: Debuff "Ensemble Fatigue" not working
### rAthena Hash

a5c3785

### Client Date

2024-10-30

### Server Mode

Renewal

### Result

Debuff "Ensemble Fatigue" not working when Bard & Dancer use skill all "Ensemble Skill" 

Description "Ensemble Fatigue" is "Exhausted when duet skill player can't use skill and decease movement speed 30%"

Image

### Relevant Log Output

```Shell

```

### Expected Result

Debuff "Ensemble Fatigue" not working when Bard & Dancer use skill all "Ensemble Skill" 

Description "Ensemble Fatigue" is "Exhausted when duet skill player can't use skill and decease movement speed 30%"

### How to Reproduce

I don't know how to doing for this, can you help me fix that?

### Official Information

In kRO server have debuff "Ensemble Fatigue" when Bard & Dancer use skill all "Ensemble Skill" 

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Lemongrass3110**
* **Addressed Issue(s)**: #7376 #9414

* **Server Mode**: Renewal

* **Description of Pull Request**: 

- Using an Ensemble Skill now properly applies Ensemble Fatique
  * Applies to both the user and the partner for 10 seconds
  * Reduces Speed and ASPD by 30%
  * Prevents usage of any skill except for "Special Singer"
- Fixes #7376 
- Fixes #9414 

Continuation of #9442, since it was closed and the underlying repository was deleted.

### CODE REVIEW

**Comment by Playtester** [comment]
Make sure you set both #9414 and #7376 to closed when you finish this PR.

File: src/map/skill.cpp [hunk 1]
```diff
@@ -18269,11 +18269,11 @@ int32 skill_check_pc_partner(map_session_data *sd, uint16 skill_id, uint16 *skil
 						clif_skill_nodamage(tsd, *sd, skill_id, *skill_lv);
 						tsd->skill_id_dance = skill_id;
 						tsd->skill_lv_dance = *skill_lv;
+					}
 #ifdef RENEWAL
-						sc_start(sd, sd, SC_ENSEMBLEFATIGUE, 100, 1, skill_get_time(CG_SPECIALSINGER, *skill_lv));
-						sc_start(sd, tsd, SC_ENSEMBLEFATIGUE, 100, 1, skill_get_time(CG_SPECIALSINGER, *skill_lv));
+					sc_start(sd, sd, SC_ENSEMBLEFATIGUE, 100, 1, skill_get_time(CG_SPECIALSINGER, *skill_lv));
+					sc_start(sd, tsd, SC_ENSEMBLEFATIGUE, 100, 1, skill_get_time(CG_SPECIALSINGER, *skill_lv));
```
Comment (Playtester) [inline src/map/skill.cpp]: This crashes at the moment because tsd is not being initialized outside the {}

Comment (Lemongrass3110) [reply src/map/skill.cpp]: Fixed

File: src/map/skill.cpp [hunk 2]
```diff
@@ -18272,7 +18272,11 @@ int32 skill_check_pc_partner(map_session_data *sd, uint16 skill_id, uint16 *skil
 					}
 #ifdef RENEWAL
 					sc_start(sd, sd, SC_ENSEMBLEFATIGUE, 100, 1, skill_get_time(CG_SPECIALSINGER, *skill_lv));
-					sc_start(sd, tsd, SC_ENSEMBLEFATIGUE, 100, 1, skill_get_time(CG_SPECIALSINGER, *skill_lv));
+
+					// If the partner is still online, also trigger fatigue on the partner
+					if( tsd != nullptr ){
```
Comment (Playtester) [inline src/map/skill.cpp]: This is not really a solution, you need to try to initialize it first.
Partner is actually always online here.

**Review by Playtester — APPROVED** [review]
Tested both pre-re and renewal, now both works as expected.

I added an improved description to the PR description too that can be used in the final commit.

File: src/map/skill.cpp [hunk 3]
```diff
@@ -18244,7 +18244,7 @@ int32 skill_check_pc_partner(map_session_data *sd, uint16 skill_id, uint16 *skil
 		return is_chorus ? MAX_PARTY : 99; //As if there were infinite partners.
 
 	if (cast_flag) {	//Execute the skill on the partners.
-		map_session_data* tsd;
+		map_session_data* tsd = nullptr;
```
Comment (Lemongrass3110) [inline src/map/skill.cpp]:
```suggestion
		map_session_data* tsd;
```
Can be reverted now again, since it is now always initialized.

File: src/map/skill.cpp [hunk 4]
```diff
@@ -18263,13 +18263,16 @@ int32 skill_check_pc_partner(map_session_data *sd, uint16 skill_id, uint16 *skil
...
-					if (c > 0 && sd->sc.getSCE(SC_DANCING) && (tsd = map_id2sd(p_sd[0])) != nullptr) {
-						sd->sc.getSCE(SC_DANCING)->val4 = tsd->id;
-						sc_start4(sd,tsd,SC_DANCING,100,skill_id,sd->sc.getSCE(SC_DANCING)->val2,*skill_lv,sd->id,skill_get_time(skill_id,*skill_lv)+1000);
-						clif_skill_nodamage(tsd, *sd, skill_id, *skill_lv);
-						tsd->skill_id_dance = skill_id;
-						tsd->skill_lv_dance = *skill_lv;
-#ifdef RENEWAL
+					if (c > 0 && (tsd = map_id2sd(p_sd[0])) != nullptr) {
+#ifndef RENEWAL
+						if (sd->sc.getSCE(SC_DANCING)) {
```
Comment (Lemongrass3110) [inline src/map/skill.cpp]:
```suggestion
						if (sd->sc.hasSCE(SC_DANCING)) {
```
