### PR TITLE
Fixed zero-length packet warning on party member logoff. Fixes #7324

### LINKED ISSUE #7324: Party packet error when relog to select char
### rAthena Hash

19fe27932f31066e8b6b025f8348cf7dc7f4deb2

### Client Date

2019-06-05fRagexe

### Server Mode

Pre-Renewal

### Result

When char has party and relog to char select in console warning packet, if don't have party member online this warning message not showing

packet_error_when_relog

### Relevant Log Output

_No response_

### Expected Result

- Warning message not show when relog to select character.

### How to Reproduce

- Join party member and relog character this warning message is show.

### Official Information

-

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by secretdataz**
* **Addressed Issue(s)**: Fixes #7324
* **Server Mode**: Both
* **Description of Pull Request**: Fixed clif_party_xy_remove calling packet_len(0x107) which is not registered in packet db causing the warning in the linked issue. Also changed the function to use packet struct instead of manual buffer writing.

### CODE REVIEW

File: src/map/clif.cpp [hunk 1]
```diff
@@ -10164,15 +10164,15 @@ void clif_disp_overhead_(struct block_list *bl, const char* mes, enum send_targe
  * Minimap fix [Kevin]
  * Remove dot from minimap
  *--------------------------*/
-void clif_party_xy_remove(struct map_session_data *sd)
+void clif_party_xy_remove(struct map_session_data* sd)
 {
-	unsigned char buf[16];
-	nullpo_retv(sd);
```
Comment (aleos89) [inline src/map/clif.cpp:10170]: Shouldn't we keep this? Just throw it up top.

**Review by vstumpf — APPROVED** [review]
