### PR TITLE
Fixed Error Messages when using Splash Skills on Skill Units

### LINKED ISSUE #5410: Napalm Beat Error
* **rAthena Hash**: faadc800423fdde8720de3d9f176d76b11c31024

* **Client Date**: 20151104a

* **Server Mode**: Pre-Re

* **Description of Issue**: 
  * Result:
`(09/21/2020 14:59:58) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!`
`(09/21/2020 14:59:58) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!`
`(09/21/2020 14:59:58) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!`
`(09/21/2020 14:59:58) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!`
`(09/21/2020 15:02:00) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!`
`(09/21/2020 15:02:00) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!`
`(09/21/2020 15:02:00) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!`
`(09/21/2020 15:02:00) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!`
`(09/21/2020 15:02:00) [ Error ] : 0 enemies targeted by 11:MG_NAPALMBEAT, divide per 0 avoided!` 
  * Expected Result: 
  * How to Reproduce: I have no idea why is this error coming out in my map-server, I haven't received any report that there might be something wrong with the skill at the moment. 
  * Official Information:
  

* **Modifications that may affect results**: None

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #5410 

* **Server Mode**: Both

**Description of Pull Request**: 

- Prevent sending 0 as number of targets when splash skills split damage among targets
  * This happened when using splash skills on skill units such as Icewall
  * Map server console will no longer be spammed with division by 0 error messages
- Fixes #5410

### CODE REVIEW

File: src/map/skill.cpp [hunk 1]
```diff
@@ -6114,8 +6114,12 @@ int32 skill_castend_damage_id (struct block_list* src, struct block_list *bl, ui
 			// if skill damage should be split among targets, count them
 			//SD_LEVEL -> Forced splash damage for Auto Blitz-Beat -> count targets
 			//special case: Venom Splasher uses a different range for searching than for splashing
-			if( flag&SD_LEVEL || skill_get_nk(skill_id, NK_SPLASHSPLIT) )
+			if (flag&SD_LEVEL || skill_get_nk(skill_id, NK_SPLASHSPLIT)) {
 				skill_area_temp[0] = map_foreachinallrange(skill_area_sub, bl, (skill_id == AS_SPLASHER)?1:splash_size, BL_CHAR, src, skill_id, skill_lv, tick, BCT_ENEMY, skill_area_sub_count);
+				// If no chars are in the area, then it always counts as if there was one target
+				// This happens when targetting skills such as icewall
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:6120]:
```suggestion
				// This happens when targetting skill units such as icewall
```

File: src/map/skill.cpp [hunk 2]
```diff
@@ -6114,8 +6114,12 @@ int32 skill_castend_damage_id (struct block_list* src, struct block_list *bl, ui
 			// if skill damage should be split among targets, count them
 			//SD_LEVEL -> Forced splash damage for Auto Blitz-Beat -> count targets
 			//special case: Venom Splasher uses a different range for searching than for splashing
-			if( flag&SD_LEVEL || skill_get_nk(skill_id, NK_SPLASHSPLIT) )
+			if (flag&SD_LEVEL || skill_get_nk(skill_id, NK_SPLASHSPLIT)) {
 				skill_area_temp[0] = map_foreachinallrange(skill_area_sub, bl, (skill_id == AS_SPLASHER)?1:splash_size, BL_CHAR, src, skill_id, skill_lv, tick, BCT_ENEMY, skill_area_sub_count);
+				// If no chars are in the area, then it always counts as if there was one target
```
Comment (Lemongrass3110) [inline src/map/skill.cpp:6119]:
```suggestion
				// If there are no characters in the area, then it always counts as if there was one target
```

**Review by Lemongrass3110 — APPROVED** [review]
