### PR TITLE
Super Novice Soul Link Base Level Checks

### LINKED ISSUE #8604: Super Novice Spirit Bug
### rAthena Hash

lastest

### Client Date

20220406

### Server Mode

Renewal

### Result

Super Novice Spirit skill doesn't allow user to wear equipment higher than their base level, Super novice sould be able to equip all Headgears and all level 4 daggers, One Handed sword, axe, mace and staff regardless of base level requirements.

### Relevant Log Output

_No response_

### Expected Result

With Spirit Super novice should be able to equip all Headgears and all level 4 daggers, One Handed sword, axe, mace and staff regardless of base level requirements.

### How to Reproduce

Use Skill Spirit Super Novice and Try wear headger or weapon with level requirement higher than 99.

### Official Information

https://www.divine-pride.net/database/skill/451

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #8604 

* **Server Mode**: Both

* **Description of Pull Request**: 

- Fixed base level requirements for SN soul link to take effect (91->90, 97->96)
- Fixed SN soul link not ignoring the item's base level restrictions
- SN soul link now allows you to equip items even if a status change would usually prevent you from doing so
- SN soul link now allows you to equip broken helmets and broken level 4 weapons
- Fixes #8604

### CODE REVIEW

**Review by Daegaladh — APPROVED** [review]

File: src/map/pc.cpp [hunk 1]
```diff
@@ -1893,6 +1891,10 @@ uint8 pc_isequip(map_session_data *sd,int n)
 		}
 	}
 
+	// Need to check this after Super Novice Link as the link overwrites minimum level restrictions
+	if (item->elv && sd->status.base_level < (unsigned int)item->elv)
```
Comment (Daegaladh) [inline src/map/pc.cpp:1895]: While you're at it, change the cast to static_cast

**Review by Lemongrass3110 — APPROVED** [review]

**Review by Daegaladh — APPROVED** [review]
