### PR TITLE
Fixes reflected damage from overflowing

### LINKED ISSUE #6693: Skill 'Reflect Damage Reduction' does damage to caster
* **rAthena Hash**: 79d978e01

* **Client Date**: 20211103

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Skill `Reflect Damage Reduction` does damage to caster when cast Lv.5 `Cannon Spear` (Only happen on my live server: Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-104-generic x86_64), If tested on my PC it not bug.)
  * Expected Result: Skill `Reflect Damage Reduction` should not damage to caster when cast Lv.5 `Cannon Spear`
  * How to Reproduce: `@job 4258
@lvup 999
@joblvup 999
@statsall 30000
@traitall
@item 530019
@item shield
@item 2105
@item 24289
@item 24578
@refine 0 99`
then had buff `Reflect Damage Reduction` and cast Lv.5 `Cannon Spear` to enemy. (Lv. <= 4 not bug)
  * Official Information: -

* **Modifications that may affect results**: -

*Checked `git diff` on live server, no changes between my PC and live server about db, src folders.

https://user-images.githubusercontent.com/9493525/158746980-e0d5b3e4-5fc6-43e3-ad87-a291d1e22048.mp4

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #6693

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Reflected damage should never be negative.
  * Reflect Damage Reduction should only reduce in normal cases (outside of WoE/BG).
  * Adjusts the variable names to better match their use.
  * General cleanups to speed up certain scenarios.
Thanks to @kaninhot004!

TODO:
- [x] Confirm if Reflect Damage Reduction reduces reflected damage to 0 or 1.

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -8224,59 +8224,57 @@ struct Damage battle_calc_attack(int attack_type,struct block_list *bl,struct bl
...
-			if (sc->data[SC_DEATHBOUND] && skill_id != WS_CARTTERMINATION && skill_id != GN_HELLS_PLANT_ATK && !status_bl_has_mode(src,MD_STATUSIMMUNE)) {
+			if (tsc->data[SC_DEATHBOUND] && skill_id != WS_CARTTERMINATION && skill_id != GN_HELLS_PLANT_ATK && !status_bl_has_mode(src,MD_STATUSIMMUNE)) {
 				if (distance_bl(src,bl) <= 0 || !map_check_dir(map_calc_dir(bl,src->x,src->y), unit_getdir(bl))) {
-					int64 rd1 = min(damage, status_get_max_hp(bl)) * sc->data[SC_DEATHBOUND]->val2 / 100; // Amplify damage.
+					int64 rd1 = min(damage, status_get_max_hp(bl)) * tsc->data[SC_DEATHBOUND]->val2 / 100; // Amplify damage.
 
 					*dmg = rd1 * 30 / 100; // Received damage = 30% of amplified damage.
-					clif_skill_damage(src, bl, gettick(), status_get_amotion(src), 0, -30000, 1, RK_DEATHBOUND, sc->data[SC_DEATHBOUND]->val1, DMG_SINGLE);
+					clif_skill_damage(src, bl, gettick(), status_get_amotion(src), 0, -30000, 1, RK_DEATHBOUND, tsc->data[SC_DEATHBOUND]->val1, DMG_SINGLE);
 					skill_blown(bl, src, skill_get_blewcount(RK_DEATHBOUND, 1), unit_getdir(src), BLOWN_NONE);
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:8278]: Shouldnt skill_get_blewcount use val1 = skill level here?

**Comment by Lemongrass3110** [comment]
Could be me, but is this a duplicate of #4352?

**Comment by aleos89** [comment]
I'll go ahead and close the older PR as it will also be addressed in this one!

**Review by Lemongrass3110 — APPROVED** [review]

**Review by Daegaladh — APPROVED** [review]
