### PR TITLE
Fixes achievements and multi level up events

### LINKED ISSUE #5413: Multi levelup ignores achievement rewards
* **rAthena Hash**: cac6121f0406e8f25faf333bc8cedcb4c9e81db6

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: When multi level up is ON and you gain more than 2 level, from a quest -> you dont get achievement rewards for that level.
  * Expected Result:  get achievement rewards
  * How to Reproduce: set yourself to level 169 -> change a quest to give you 1.000.000.000 EXP as reward -> complete the quest and you end up being around 171-175 BUT **you dont complete the level 170 achievement** and cant claim the reward for it
  * Official Information:
  

* **Modifications that may affect results**:

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #5413

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Fixes an issue where achievements that check for specific base/job level events don't get triggered if battle_config.multi_level_up is enabled.
Thanks to @saya9200!

### CODE REVIEW

**Comment by saya9200** [comment]
IDK if it's just on my live server like this. I have some modifications but not really achievement related.

1) I complete quest "12345" // but I dont have an achievement reward set for it yet.

2) Add a new achievement to the server that requires this quest to be complete.

3) server goes up -> you login with the char that completed the quest -> but dont get the achievement for it.

File: src/map/atcommand.cpp [hunk 1]
```diff
@@ -1559,8 +1559,10 @@ ACMD_FUNC(baselevelup)
 		status_calc_pc(sd, SCO_FORCE);
 		status_percent_heal(&sd->bl, 100, 100);
 		clif_misceffect(&sd->bl, 0);
-		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, sd->status.base_level);
-		achievement_update_objective(sd, AG_GOAL_STATUS, 2, sd->status.base_level, sd->status.class_);
+		for (uint16 i = 1; i <= (sd->status.base_level - level); i++) {
```
Comment (Lemongrass3110) [inline src/map/atcommand.cpp:1562]:
```suggestion
		for (uint16 i = sd->status.base_level - level; i <= sd->status.base_level; i++) {
```

File: src/map/atcommand.cpp [hunk 2]
```diff
@@ -1559,8 +1559,10 @@ ACMD_FUNC(baselevelup)
...
+			achievement_update_objective(sd, AG_GOAL_LEVEL, 1, level + i);
```
Comment (Lemongrass3110) [inline src/map/atcommand.cpp:1563]:
```suggestion
			achievement_update_objective(sd, AG_GOAL_LEVEL, 1, i);
```

File: src/map/atcommand.cpp [hunk 3]
```diff
@@ -1559,8 +1559,10 @@ ACMD_FUNC(baselevelup)
...
+			achievement_update_objective(sd, AG_GOAL_STATUS, 2, level + i, sd->status.class_);
```
Comment (Lemongrass3110) [inline src/map/atcommand.cpp:1564]:
```suggestion
			achievement_update_objective(sd, AG_GOAL_STATUS, 2, i, sd->status.class_);
```

File: src/map/atcommand.cpp [hunk 4]
```diff
@@ -1622,7 +1624,8 @@ ACMD_FUNC(joblevelup)
 		sd->status.job_level += (unsigned int)level;
 		sd->status.skill_point += level;
 		clif_misceffect(&sd->bl, 1);
-		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, sd->status.job_level);
+		for (uint16 i = 1; i <= (sd->status.job_level - level); i++)
```
Comment (Lemongrass3110) [inline src/map/atcommand.cpp:1627]:
```suggestion
		for (uint16 i = sd->status.job_level - level; i <= sd->status.job_level; i++)
```

File: src/map/atcommand.cpp [hunk 5]
```diff
@@ -1622,7 +1624,8 @@ ACMD_FUNC(joblevelup)
...
+			achievement_update_objective(sd, AG_GOAL_LEVEL, 1, level + i);
```
Comment (Lemongrass3110) [inline src/map/atcommand.cpp:1628]:
```suggestion
			achievement_update_objective(sd, AG_GOAL_LEVEL, 1, i);
```

File: src/map/pc.cpp [hunk 6]
```diff
@@ -7093,8 +7095,10 @@ int pc_checkbaselevelup(struct map_session_data *sd) {
 		party_send_levelup(sd);
 
 	pc_baselevelchanged(sd);
-	achievement_update_objective(sd, AG_GOAL_LEVEL, 1, sd->status.base_level);
-	achievement_update_objective(sd, AG_GOAL_STATUS, 2, sd->status.base_level, sd->status.class_);
+	for (uint16 i = 1; i <= (sd->status.base_level - base_level); i++) {
```
Comment (Lemongrass3110) [inline src/map/pc.cpp:7098]:
```suggestion
	for (; base_level <= sd->status.base_level; base_level++) {
```

File: src/map/pc.cpp [hunk 7]
```diff
@@ -7093,8 +7095,10 @@ int pc_checkbaselevelup(struct map_session_data *sd) {
...
+		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, base_level + i);
```
Comment (Lemongrass3110) [inline src/map/pc.cpp:7099]:
```suggestion
		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, base_level);
```

File: src/map/pc.cpp [hunk 8]
```diff
@@ -7093,8 +7095,10 @@ int pc_checkbaselevelup(struct map_session_data *sd) {
...
+		achievement_update_objective(sd, AG_GOAL_STATUS, 2, base_level + i, sd->status.class_);
```
Comment (Lemongrass3110) [inline src/map/pc.cpp:7100]:
```suggestion
		achievement_update_objective(sd, AG_GOAL_STATUS, 2, base_level, sd->status.class_);
```

File: src/map/pc.cpp [hunk 9]
```diff
@@ -7142,7 +7148,8 @@ int pc_checkjoblevelup(struct map_session_data *sd)
 		clif_status_change(&sd->bl, EFST_DEVIL1, 1, 0, 0, 0, 1); //Permanent blind effect from SG_DEVIL.
 
 	npc_script_event(sd, NPCE_JOBLVUP);
-	achievement_update_objective(sd, AG_GOAL_LEVEL, 1, sd->status.job_level);
+	for (uint16 i = 1; i <= (sd->status.job_level); i++)
```
Comment (Lemongrass3110) [inline src/map/pc.cpp:7151]:
```suggestion
	for (; job_level <= sd->status.job_level; job_level++)
```

File: src/map/pc.cpp [hunk 10]
```diff
@@ -7142,7 +7148,8 @@ int pc_checkjoblevelup(struct map_session_data *sd)
...
+		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, job_level + 1);
```
Comment (Lemongrass3110) [inline src/map/pc.cpp:7152]:
```suggestion
		achievement_update_objective(sd, AG_GOAL_LEVEL, 1, job_level);
```

**Review by Lemongrass3110 — CHANGES_REQUESTED** [review]

**Comment by Lemongrass3110** [comment]
> 
> 
> IDK if it's just on my live server like this. I have some modifications but not really achievement related.
> 
>     1. I complete quest "12345" // but I dont have an achievement reward set for it yet.
> 
>     2. Add a new achievement to the server that requires this quest to be complete.
> 
>     3. server goes up -> you login with the char that completed the quest -> but dont get the achievement for it.

Create a seperate issue for this and give a sample YML entry so we can test.
It is hard to tell what is wrong if you do not say how you even check the quest state.

**Review by Lemongrass3110 — APPROVED** [review]

**Comment by BotGigo** [comment]
This issue still present today, im using a very fresh version of rathena.

imagen
