### PR TITLE
Resolves spawn direction not saving at relog

### LINKED ISSUE #7195: "spawn_direction = yes" is not applied when logging in
* **rAthena Hash**: 
Latest
* **Client Date**: 

20211103

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: "spawn_direction =yes" is not respected when logging in
  * Expected Result: Character's last facing direction should be respected when  a player teleports, changes maps, or **logs in**
  * How to Reproduce: Set "spawn_direction: yes", reloadbattleconf, try facing south, disconnecting and reconnecting.
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  

https://user-images.githubusercontent.com/7357354/185729757-4ed642c4-ab10-4f25-bb7e-9c65aba0f4c9.mp4

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #7195

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Adds a new save field for battle config spawn_direction which was not working for players who log out and in.
Thanks to @SapitoSucio!

### CODE REVIEW

File: sql-files/upgrades/upgrade_20220825.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+ALTER TABLE `mob_db`
```
Comment (Melk3000) [inline sql-files/upgrades/upgrade_20220825.sql:1]: why did you modify the mob_db table?

Comment (aleos89) [reply sql-files/upgrades/upgrade_20220825.sql]: Was a copy-paste mistake.

File: src/map/unit.cpp [hunk 2]
```diff
@@ -1109,8 +1107,14 @@ int unit_setdir(struct block_list *bl, unsigned char dir)
 
 	ud->dir = dir;
 
-	if (bl->type == BL_PC)
-		((TBL_PC *)bl)->head_dir = 0;
+	if (bl->type == BL_PC) {
+		map_session_data *sd = map_id2sd(bl->id);
+
+		if (sd != nullptr) {
+			sd->head_dir = 0;
```
Comment (Lemongrass3110) [inline src/map/unit.cpp:1114]:
```suggestion
			sd->head_dir = DIR_NORTH;
```

File: src/map/clif.cpp [hunk 3]
```diff
@@ -11045,6 +11045,9 @@ void clif_parse_LoadEndAck(int fd,struct map_session_data *sd)
 			//Login Event
 			npc_script_event(sd, NPCE_LOGIN);
 		}
+
+		// Set facing direction before battle_config.spawn_direction
+		sd->ud.dir = sd->status.dir;
```
Comment (Lemongrass3110) [inline src/map/clif.cpp:11050]: Why not unit_setdir?

Comment (Lemongrass3110) [reply src/map/clif.cpp:11050]: Also the question is if you should actually do that only if the config is enabled?
Because otherwise server and client direction are out of sync or not?

**Review by Lemongrass3110 — APPROVED** [review]

**Review by vstumpf — APPROVED** [review]

**Comment by SapitoSucio** [comment]
I applied the PR and I'm getting this 
image

It sends me to guild_vs1

https://user-images.githubusercontent.com/7357354/187350095-b8dced1e-0d54-43bc-8be8-ef8fa95ad66d.mp4
