### PR TITLE
Cloaking / Power Maximize on Monsters

### LINKED ISSUE #9316: Cloaking / Power Maximize on Monsters should not be infinite
### rAthena Hash

1ce2acf

### Client Date

2021-11-03

### Server Mode

Pre-Renewal, Renewal

### Result

When a monster uses Cloaking / Power Maximize, it never ends, unless it attacks or casts it again.

### Expected Result

When a monster uses Cloaking / Power Maximize, it ends after 10 seconds.

### How to Reproduce

Equip Maya Purple Card, aggro a Hode, when it uses Cloaking, run out of chase range. Then wait until the Cloaking effect ends.

Make a monster cast Power Maximize and measure when the damage returns to normal.

### Official Information

Verified on official servers by testing.

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9316 

* **Server Mode**: Both

* **Description of Pull Request**: 

- Fixed duration of Cloaking / Power Maximize being infinite for monsters
  * The duration is now fixed to 10 seconds
- Fixes #9316

### CODE REVIEW

File: src/map/status.cpp [hunk 1]
```diff
@@ -11139,10 +11145,15 @@ int32 status_change_start(struct block_list* src, struct block_list* bl,enum sc_
 			if (map_flag_gvg2(bl->m) || map_getmapflag(bl->m, MF_BATTLEGROUND)) val4 *= 5;
 			break;
 		case SC_CLOAKING:
-			if (!sd) // Monsters should be able to walk with no penalties. [Skotlex]
+			if (sd == nullptr) {
+				// Monsters have no walk penalties and the status change lasts for 10 seconds
```
Comment (Lemongrass3110) [inline src/map/status.cpp:11149]:
```suggestion
				// Non-players have no walk penalties and the status change lasts for 10 seconds
```

File: src/map/status.cpp [hunk 2]
```diff
@@ -11139,10 +11145,15 @@ int32 status_change_start(struct block_list* src, struct block_list* bl,enum sc_
...
 				val1 = 10;
-			tick_time = val2 = tick>0?tick:60000; // SP consumption rate.
-			tick = INFINITE_TICK; // Duration sent to the client should be infinite
+				tick = 10000;
+			}
+			else {
+				tick_time = val2 = tick>0?tick:10000; // SP consumption rate.
```
Comment (Lemongrass3110) [inline src/map/status.cpp:11154]:
```suggestion
				tick_time = val2 = tick>0?tick:10000; // SP consumption intervall.
```

**Review by Lemongrass3110 — APPROVED** [review]
Would be nice to invert the two ifs and not have the "edge" case first.

File: src/map/status.cpp (hunk 1 above)
Comment (Playtester) [reply src/map/status.cpp:11149]: Actually good point, I should check how other types behave here.

**Comment by Playtester** [comment]
> Would be nice to invert the two ifs and not have the "edge" case first.

Done!

Also I changed it so that all units that can consume SP use the normal skill behavior, rather than using the 10 seconds version for all non-PC types.

Mercenaries, Homunculus and Elementals don't use these skills officially, but it's cleaner for customization like this.

**Comment by Lemongrass3110** [comment]
Even better now :)
