### PR TITLE
Fixes renewal weapon attack display

### LINKED ISSUE #554: RE: Weapon attack bonus from Strength/Dexterity Display Issue
this is also similar to Critical Display wearing a Katar Weapon but this time it is Weapon Attack bonus from stats that must be hidden from Status Window (Alt+A or Alt+Q)

note:
to reproduce you must wear weapon to display additional weapon attack.

### LINKED ISSUE #578: Strength/Dexterity weapon atk bonus from Buffs, Foods and Runes does not apply
as we know rAthena designed it so that weapon atk bonus from status are visible , problem is none of atk bonus (weapon atk) from stats ( buffs/foods/runes ) apply in the status window i don't know if this intended or a bug but im gonna report it anyway. ^^

screenjamro073

### LINKED ISSUE #909: Incorrect weapon Attack
I did a test on bRO and rAthena  and noticed a bug in weapon attack follows the image
16005,P_Mace2,Eden Mace II,5,0,,0,163,,1,0,0x0004C5B2,63,2,2,2,40,0,8,{},{},{}
The script is correct 163 attack but to equip note the difference
BRO:
bro bug
Rathena:
rathena

Version: 22a9a74
Client : 20130807
model : renewal

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #554, fixes #578, and fixes #909

* **Server Mode**: Renewal

* **Description of Pull Request**: 
  * The right hand attack display should only show bonuses given by weapons and not the STR/DEX bonus.
Thanks to @reigneil, @Paoly28, @panko11, and @limitro!

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -2090,14 +2090,36 @@ static int battle_calc_base_weapon_attack(struct block_list *src, struct status_
...
 	uint16 atkmax = atkmin;
 	int64 damage = atkmin;
-	uint16 weapon_perfection = 0;
+	bool weapon_perfection = false;
 	struct status_change *sc = status_get_sc(src);
 
 	if (sd->equip_index[type] >= 0 && sd->inventory_data[sd->equip_index[type]]) {
-		int variance =   wa->atk * (sd->inventory_data[sd->equip_index[type]]->wlv*5)/100;
+		short base_stat;
+		bool ranged = false;
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:2098]:
```suggestion
```

File: src/map/battle.cpp [hunk 2]
```diff
@@ -2090,14 +2090,36 @@ static int battle_calc_base_weapon_attack(struct block_list *src, struct status_
...
+		switch (sd->status.weapon) {
+			case W_BOW:
+			case W_MUSICAL:
+			case W_WHIP:
+			case W_REVOLVER:
+			case W_RIFLE:
+			case W_GATLING:
+			case W_SHOTGUN:
+			case W_GRENADE:
+				ranged = true;
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:2109]:
```suggestion
				base_stat = status->dex;
				break;
			default:
				base_stat = status->str;
				break;
```

File: src/map/battle.cpp [hunk 3]
```diff
@@ -2090,14 +2090,36 @@ static int battle_calc_base_weapon_attack(struct block_list *src, struct status_
...
+				break;
+		}
+
+		if (ranged)
+			base_stat = status->dex;
+		else
+			base_stat = status->str;
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:2116]:
```suggestion
```

**Review by Lemongrass3110 — APPROVED** [review]
