### PR TITLE
Fixes monster Sharp Shooting damage formula

### LINKED ISSUE #5769: Mob casted SN_SHARPSHOOTING should be a lot stronger
* **rAthena Hash**: latest
* **Client Date**: x
* **Server Mode**: both!
* **Description of Issue**: 
  * Result: Mobs are getting the same damage output on SN_SHARPSHOOTING as players
  * Expected Result: Do proper damage!
  * How to Reproduce: summon a Cecil and get wrecked, I suppose
  * Official Information: Mob casted SN_SHARPSHOOTING damage is `140 * skLevel (140-700%)` as long as it hits in its 8path splash. When it uses the fallback single target it, the original ratio `(250-450%)` is used. Recently the Ratio for RE was updated, so this will require further testing that's unavailable to me, sorry. The best solution for this I can think of is to give mobs the 8path splash, and flag when it's a single skill_attack to switch to the player/merc ratio. For Pre-RE this can be fixed right away but for Renewal we need more info..

* **Modifications that may affect results**: x

### PR DESCRIPTION
**Pull request by aleos89**
* **Addressed Issue(s)**: Fixes #5769

* **Server Mode**: Pre-renewal and Renewal

* **Description of Pull Request**: 
  * Adjusts the formula for Sharp Shooting if a monster uses the skill.
Thanks to @mrjnumber1!

### CODE REVIEW

**Review by Lemongrass3110 — APPROVED** [review]

File: src/map/battle.cpp [hunk 1]
```diff
@@ -4108,12 +4108,19 @@ static int battle_calc_attack_skill_ratio(struct Damage* wd, struct block_list *
 			break;
 		case SN_SHARPSHOOTING:
 		case MA_SHARPSHOOTING:
+			if (src->type == BL_MOB) { // TODO: Did these formulas change in the renewal balancing?
+				if (battle_config.skill_eightpath_algorithm == 1)
+					skillratio += 40 * skill_lv;
+				else
+					skillratio += 100 + 50 * skill_lv;
```
Comment (vstumpf) [inline src/map/battle.cpp:4115]: I'm not sure this is right, I think @mrjnumber1 was saying the damage increases if the target is in an eight-path direction from the source.

If the source is at (0,0), a target at (4,4) will take extra damage, and a target at (7, 3) will take less damage.

Comment (aleos89) [reply src/map/battle.cpp:4115]: Good point! I didn’t read it like that!

**Review by Lemongrass3110 — APPROVED** [review]
Seeing all the ifs for skill_id == SN_SHARPSHOOTING I would suggest thinking about creating its own case and duplicate the code maybe...
