### PR TITLE
Fixed Basilica Blocking Attacks in Renewal

### LINKED ISSUE #9220: Skill Basilica Bug
### rAthena Hash

a5c3785

### Client Date

2024-10-30

### Server Mode

Renewal

### Result

Image

When uesd skill "Basilica" Job "High Priest" show state icon buff but can't melee attack monster
In description skill is "Increases Holy Magic Damage and Physical Attack dealt to Shadow and Undead"

### Relevant Log Output

```Shell

```

### Expected Result

If have SC_BASILICA can melee attack monster

### How to Reproduce

I don't know how to reproduce, pls help me to fix that

### Official Information

From kRO server

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9220 

* **Server Mode**: Renewal

**Description of Pull Request**: 

- Basilica is no longer blocking attacks in renewal
- Removed unused status change SC_BASILICA_CELL
  * The skill is just a self-buff in renewal, no units are placed
- Fixes #9220

### CODE REVIEW

**Review by secretdataz — APPROVED** [review]

**Comment by Jaikayray** [comment]
Thank you to help me fix that

I'm confirm it's work 100%

File: src/map/script_constants.hpp [hunk 1]
```diff
@@ -1651,7 +1651,6 @@
 	export_constant(SC_ENTRY_QUEUE_APPLY_DELAY);
 	export_constant(SC_ENTRY_QUEUE_NOTIFY_ADMISSION_TIME_OUT);
 	export_constant(SC_ADAPTATION);
-	export_constant(SC_BASILICA_CELL);
```
Comment (Lemongrass3110) [inline src/map/script_constants.hpp:1654]: Since you leave it in status.hpp as well, may be good to deprecate it only too.

File: src/map/status.hpp [hunk 2]
```diff
@@ -1031,9 +1031,9 @@ enum sc_type : int16 {
 	SC_WEAPONBLOCK_ON,
 	SC_SPORE_EXPLOSION,
 	SC_ADAPTATION,
-	SC_BASILICA_CELL, // Used in renewal mode for cell_basilica only
+	//SC_BASILICA_CELL,
```
Comment (Lemongrass3110) [inline src/map/status.hpp:1034]: Maybe leave it uncommented and we remove it after the deprecation of script_constants.hpp has run out (2 years)?

File: src/map/battle.cpp [hunk 3]
```diff
@@ -1415,12 +1415,9 @@ bool battle_status_block_damage(struct block_list *src, struct block_list *targe
 	}
 
 	if ((sc->getSCE(SC_PNEUMA) && (flag&(BF_MAGIC | BF_LONG)) == BF_LONG) ||
-#ifdef RENEWAL
-		(sc->getSCE(SC_BASILICA_CELL)
-#else
-		(sc->getSCE(SC_BASILICA)
+#ifndef RENEWAL
+		(sc->getSCE(SC_BASILICA) != nullptr && !status_bl_has_mode(src, MD_STATUSIMMUNE) && skill_id != SP_SOULEXPLOSION) ||
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:1419]: SP_SOULEXPLOSION is a renewal skill.
Should we really leave this?

**Review by Lemongrass3110 — APPROVED** [review]
