### PR TITLE
Corrected NPC_DARKBREATH formula

### LINKED ISSUE #7284: NPC_DARKBREATH has an incorrect formula
### rAthena Hash

4800b5bf725fe9fe68cb75a8d0d3f4c7252e3cc8

### Client Date

N/A

### Server Mode

Pre-Renewal, Renewal

### Result

The NPC_DARKBREATH formula is flawed, so the skill does much less damage than expected ( 50% current hp )

### Relevant Log Output

_No response_

### Expected Result

N/A

### How to Reproduce

N/A

### Official Information

https://irowiki.org/classic/NPC_DARKBREATH

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Singe-Horizontal**
* **Addressed Issue(s)**: 
Fixes #7284

* **Server Mode**: 
Both

* **Description of Pull Request**: 
Corrects the NPC_DARKBREATH math formula

### CODE REVIEW

File: src/map/battle.cpp [hunk 1]
```diff
@@ -6978,7 +6978,7 @@ struct Damage battle_calc_magic_attack(struct block_list *src,struct block_list
 				}
 				break;
 			case NPC_DARKBREATH:
-				ad.damage = tstatus->hp * (skill_lv <= 5 ? 100 / (2 * 6 - skill_lv) : 50) / 100;
+			        ad.damage = tstatus->hp * (skill_lv <= 5 ? 100 / (2 * (6 - skill_lv)) : 50) / 100;
```
Comment (Pokye) [inline src/map/battle.cpp:6981]:
```suggestion
				ad.damage = tstatus->hp * (skill_lv <= 5 ? 100 / (2 * (6 - skill_lv)) : 50) / 100;
```
Remove <SPACE> and add <TAB>

File: src/map/battle.cpp [hunk 2]
```diff
@@ -6978,7 +6978,7 @@ struct Damage battle_calc_magic_attack(struct block_list *src,struct block_list
 				}
 				break;
 			case NPC_DARKBREATH:
-				ad.damage = tstatus->hp * (skill_lv <= 5 ? 100 / (2 * 6 - skill_lv) : 50) / 100;
+				ad.damage = tstatus->hp * (skill_lv <= 5 ? 100 / (2 * (6 - skill_lv)) : 50) / 100;
```
Comment (Lemongrass3110) [inline src/map/battle.cpp:6981]:
```suggestion
				ad.damage = ( tstatus->hp * std::min( 10 * skill_lv, 50 ) ) / 100;
```
I would rather like to simplify the formula as a whole?

**Review by Lemongrass3110 — APPROVED** [review]

**Comment by Singe-Horizontal** [comment]
Is anyone available to confirm this on aegis?

**Comment by Singe-Horizontal** [comment]
I assumed you meant 2 * (6-skLevel) since it makes sense with the initial skLevel <= 5 test

**Comment by Daegaladh** [comment]
Not sure if it's `2*(6-skLevel)` or `2*6-skLevel`, but if it's really the first case, there's no need to split it into pre-re/re
https://github.com/rathena/rathena/issues/4864#issuecomment-629578983

**Comment by Singe-Horizontal** [comment]
In RE with that formula it would give : 10% 12,5% 16,67% 25% 50%

**Comment by Daegaladh** [comment]
I know, 2*(6-skLevel) would make more sense, but need confirmation

**Review by aleos89 — APPROVED** [review]

**Review by Daegaladh — CHANGES_REQUESTED** [review]
We've confirmed it's `2*(6 - skill_lv)` , just remove the pre-re/re ifdef, as they're not necessary, it's the same for both

**Review by Daegaladh — APPROVED** [review]
