### PR TITLE
CastCancel Attribute Fixes

### LINKED ISSUE #9023: Skills (Shield Chain, Magic Power, Ganbantein, etc.) should be cast-interuptable
### rAthena Hash

7aa82c9

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

Shield Chain (Rapid Smiting) cannot be cast-interupted.
Magic Power cannot be cast-interupted.
Ganbantein cannot be cast-interupted

### Expected Result

Shield Chain (Rapid Smiting) can be cast-interupted.
Magic Power can be cast-interupted.
Ganbantein can be cast-interupted

Also many other skills:
Image

### How to Reproduce

Use above skills while getting attacked.

### Official Information

Confirmed for several skills (see picture above).

### Modifications that may affect results

_No response_

### PR DESCRIPTION
**Pull request by Playtester**
* **Addressed Issue(s)**: #9023 

* **Server Mode**: Both

**Description of Pull Request**: 

- The CastCancel attribute now defaults to "true"
- Corrected the list of skills that cannot be cast-canceled (fixes #9023)
  * Please see linked issue for a complete list of skill changes

### CODE REVIEW

File: src/tool/yamlupgrade.cpp [hunk 1]
```diff
@@ -524,6 +531,34 @@ static bool upgrade_item_group_db( std::string file, const uint32 source_version
 	return true;
 }
 
+static bool upgrade_skill_db( std::string file, const uint32 source_version ){
+	size_t entries = 0;
+
+	for( auto input : inNode["Body"] ){
+		// If under version 4
+		if( source_version < 4 ){
+			// Rename End to EndOnStart
```
Comment (aleos89) [inline src/tool/yamlupgrade.cpp:540]:
```suggestion
```

**Review by aleos89 — APPROVED** [review]
